CREATE WAREHOUSE PROJECT_16_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE PROJECT_16_WH;

CREATE OR REPLACE DATABASE PROJECT_16_DB;

USE DATABASE PROJECT_16_DB;

CREATE OR REPLACE SCHEMA PROJECT_16_SCHEMA;

USE SCHEMA PROJECT_16_SCHEMA;


CREATE OR REPLACE FILE FORMAT FF_JSON
TYPE = JSON;

CREATE OR REPLACE STAGE CLAIMS_RAW
FILE_FORMAT = FF_JSON;

---------BRONZE TABLE CREATION
CREATE OR REPLACE TABLE BRONZE_RAW_CLAIMS
(
    INGEST_ID NUMBER AUTOINCREMENT,
    PAYLOAD VARIANT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO BRONZE_RAW_CLAIMS (PAYLOAD)
FROM @CLAIMS_RAW/batch1.json
FILE_FORMAT = (FORMAT_NAME = FF_JSON)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO BRONZE_RAW_CLAIMS (PAYLOAD)
FROM @CLAIMS_RAW/batch2.json
FILE_FORMAT = (FORMAT_NAME = FF_JSON)
ON_ERROR = 'ABORT_STATEMENT';

-----------------loading batch 3

--------a.Creating quarantine table
CREATE OR REPLACE TABLE QUARANTINE_CLAIMS_PAYLOADS
(
    QUARANTINE_ID NUMBER AUTOINCREMENT,
    RAW_RECORD_TEXT STRING,
    REASON STRING
);
----------b. Creating text file format

CREATE OR REPLACE FILE FORMAT FF_CLAIMS_TEXT
TYPE = CSV
FIELD_DELIMITER = NONE
RECORD_DELIMITER = '\n'
SKIP_HEADER = 0;

------------c.Read batch 3 as text

SELECT
    $1 AS RAW_RECORD_TEXT
FROM @CLAIMS_RAW/batch3.json
(
    FILE_FORMAT => 'FF_CLAIMS_TEXT'
);

-- --------d.Apply TRY_PARSE_JSON()
SELECT
    $1 AS RAW_RECORD_TEXT,
    TRY_PARSE_JSON($1) AS PARSED_JSON
FROM @CLAIMS_RAW/batch3.json
(
    FILE_FORMAT => 'FF_CLAIMS_TEXT'
);

-- e.Load Valid Batch 3 Record into Bronze
INSERT INTO BRONZE_RAW_CLAIMS
(
    PAYLOAD
)
SELECT
    TRY_PARSE_JSON($1)
FROM @CLAIMS_RAW/batch3.json
(
    FILE_FORMAT => 'FF_CLAIMS_TEXT'
)
WHERE TRY_PARSE_JSON($1) IS NOT NULL;

------------f.Validating count
SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS
FROM BRONZE_RAW_CLAIMS;

------------g.Putting invalid record into Quarantine
INSERT INTO QUARANTINE_CLAIMS_PAYLOADS
(
    RAW_RECORD_TEXT,
    REASON
)
SELECT
    $1,
    'MALFORMED_JSON_BODY'
FROM @CLAIMS_RAW/batch3.json
(
    FILE_FORMAT => 'FF_CLAIMS_TEXT'
)
WHERE TRY_PARSE_JSON($1) IS NULL;

--------- Silver Layer — Real-Time CDC via Stream Tracking
CREATE OR REPLACE STREAM STRM_BRONZE_CLAIMS
ON TABLE BRONZE_RAW_CLAIMS;

--------------B. STREAM CHECKING
SHOW STREAMS LIKE 'STRM_BRONZE_CLAIMS';

-----------Silver base table
CREATE OR REPLACE TABLE SILVER_CLAIMS_TRANSACTIONS
(
    CLAIM_ID STRING,
    SUBMITTED_AT TIMESTAMP_TZ,
    PATIENT_ID NUMBER,
    PROVIDER_ID STRING,
    DIAGNOSIS_CODE STRING,
    BILLED_AMOUNT NUMBER(12,2),
    COPAY_AMOUNT NUMBER(12,2),
    NET_PAYABLE_AMOUNT NUMBER(12,2),
    STATUS STRING
);

---------INSERTING ONLY LATEST RECORDS AND REMOVING DUPLICATES BY USING RANK

INSERT INTO SILVER_CLAIMS_TRANSACTIONS
(
    CLAIM_ID,
    SUBMITTED_AT,
    PATIENT_ID,
    PROVIDER_ID,
    DIAGNOSIS_CODE,
    BILLED_AMOUNT,
    COPAY_AMOUNT,
    NET_PAYABLE_AMOUNT,
    STATUS
)
SELECT
    CLAIM_ID,
    SUBMITTED_AT,
    PATIENT_ID,
    PROVIDER_ID,
    DIAGNOSIS_CODE,
    BILLED_AMOUNT,
    COPAY_AMOUNT,
    BILLED_AMOUNT - COPAY_AMOUNT AS NET_PAYABLE_AMOUNT,
    STATUS
FROM
(
    SELECT
        PAYLOAD:claim_id::STRING AS CLAIM_ID,
        PAYLOAD:submitted_at::TIMESTAMP_TZ AS SUBMITTED_AT,
        PAYLOAD:patient_id::NUMBER AS PATIENT_ID,
        PAYLOAD:provider_id::STRING AS PROVIDER_ID,
        PAYLOAD:diagnosis_code::STRING AS DIAGNOSIS_CODE,
        PAYLOAD:billed_amount::NUMBER(12,2) AS BILLED_AMOUNT,
        PAYLOAD:copay_amount::NUMBER(12,2) AS COPAY_AMOUNT,
        PAYLOAD:status::STRING AS STATUS,

        ROW_NUMBER() OVER
        (
            PARTITION BY PAYLOAD:claim_id::STRING
            ORDER BY INGEST_ID DESC
        ) AS RN

    FROM BRONZE_RAW_CLAIMS
)
WHERE RN = 1;

SELECT *
FROM SILVER_CLAIMS_TRANSACTIONS
ORDER BY CLAIM_ID;

-----------DYNAMIC TABLE CREATION
CREATE OR REPLACE DYNAMIC TABLE DT_PROVIDER_FINANCIAL_SUMMARY
TARGET_LAG = '1 MINUTE'
WAREHOUSE = PROJECT_16_WH
AS
SELECT
    PROVIDER_ID,

    SUM(BILLED_AMOUNT) AS TOTAL_BILLED_AMOUNT,

    SUM(COPAY_AMOUNT) AS TOTAL_COPAY_AMOUNT,

    SUM(NET_PAYABLE_AMOUNT) AS TOTAL_NET_PAYABLE_AMOUNT,

    COUNT(*) AS APPROVED_CLAIM_COUNT

FROM SILVER_CLAIMS_TRANSACTIONS

WHERE STATUS = 'APPROVED'

GROUP BY PROVIDER_ID;

-----------Querying dynamic table

SELECT *
FROM DT_PROVIDER_FINANCIAL_SUMMARY
ORDER BY PROVIDER_ID;

-- Dynamic Table Refresh Monitoring & DAG Audit

----a.Refresh Monitoring
SELECT
    NAME,
    DATA_TIMESTAMP,
    REFRESH_START_TIME,
    REFRESH_END_TIME,
    REFRESH_ACTION,
    STATE,
    REFRESH_TRIGGER
FROM TABLE(
    INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
        NAME => 'DT_PROVIDER_FINANCIAL_SUMMARY'
    )
)
ORDER BY REFRESH_START_TIME DESC;

------b.DAG HISTORY
SELECT
    NAME,
    INPUTS,
    TARGET_LAG_TYPE,
    TARGET_LAG_SEC,
    SCHEDULING_STATE,
    VALID_FROM,
    VALID_TO,
    ALTER_TRIGGER
FROM TABLE(
    INFORMATION_SCHEMA.DYNAMIC_TABLE_GRAPH_HISTORY()
)
WHERE NAME = 'DT_PROVIDER_FINANCIAL_SUMMARY'
ORDER BY VALID_FROM DESC;

---------C.Refresh History
SELECT
    NAME,
    REFRESH_ACTION,
    STATE,
    REFRESH_TRIGGER,
    DATA_TIMESTAMP,
    REFRESH_START_TIME,
    REFRESH_END_TIME
FROM TABLE(
    INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
        NAME => 'DT_PROVIDER_FINANCIAL_SUMMARY'
    )
)
ORDER BY REFRESH_START_TIME DESC;


SHOW DYNAMIC TABLES LIKE 'DT_PROVIDER_FINANCIAL_SUMMARY';

-----------Final Reconciliation
SELECT
    (
        SELECT SUM(PAYLOAD:billed_amount::NUMBER(12,2))
        FROM BRONZE_RAW_CLAIMS
    ) AS BRONZE_GROSS_TOTAL,

    (
        SELECT SUM(BILLED_AMOUNT)
        FROM SILVER_CLAIMS_TRANSACTIONS
    ) AS SILVER_GROSS_TOTAL,

    (
        SELECT SUM(TOTAL_BILLED_AMOUNT)
        FROM DT_PROVIDER_FINANCIAL_SUMMARY
    ) AS GOLD_GROSS_TOTAL,

    CASE
        WHEN
            (
                SELECT SUM(PAYLOAD:billed_amount::NUMBER(12,2))
                FROM BRONZE_RAW_CLAIMS
            ) = 257700
        AND
            (
                SELECT SUM(BILLED_AMOUNT)
                FROM SILVER_CLAIMS_TRANSACTIONS
            ) = 197700
        AND
            (
                SELECT SUM(TOTAL_BILLED_AMOUNT)
                FROM DT_PROVIDER_FINANCIAL_SUMMARY
            ) = 152700
        THEN TRUE
        ELSE FALSE
    END AS RECONCILED_FLAG;