USE WAREHOUSE SNOW_WH;

CREATE OR REPLACE DATABASE CUSTOMER_MEMBERSHIP_DW;

USE DATABASE CUSTOMER_MEMBERSHIP_DW;

CREATE OR REPLACE SCHEMA CUSTOMER_SCHEMA;

USE SCHEMA CUSTOMER_SCHEMA;

CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
TRIM_SPACE = TRUE
NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE CUSTOMER_STAGE
FILE_FORMAT = CUSTOMER_CSV_FORMAT;

LIST @CUSTOMER_STAGE;

CREATE OR REPLACE TABLE STG_CUSTOMERS_INITIAL (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);

CREATE OR REPLACE TABLE STG_CUSTOMER_UPDATES (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);


/* =====================================================================
   TASK 6 — LOAD INITIAL CUSTOMER DATA
   ===================================================================== */

COPY INTO STG_CUSTOMERS_INITIAL
FROM @CUSTOMER_STAGE/customers_initial.csv
FILE_FORMAT = CUSTOMER_CSV_FORMAT;


/* =====================================================================
   TASK 7 — LOAD CUSTOMER UPDATE DATA
   ===================================================================== */

COPY INTO STG_CUSTOMER_UPDATES
FROM @CUSTOMER_STAGE/customer_updates.csv
FILE_FORMAT = CUSTOMER_CSV_FORMAT;


/* =====================================================================
   TASK 8 — VALIDATE STAGING DATA
   ===================================================================== */

SELECT
    COUNT(*) AS INITIAL_CUSTOMER_COUNT
FROM STG_CUSTOMERS_INITIAL;


SELECT
    COUNT(*) AS UPDATE_RECORD_COUNT
FROM STG_CUSTOMER_UPDATES;


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM STG_CUSTOMERS_INITIAL
ORDER BY CUSTOMER_ID;


/* =====================================================================
   TASK 10 — DISPLAY CUSTOMER UPDATE DATA
   ===================================================================== */

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE
FROM STG_CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID;


CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE3 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);

INSERT INTO DIM_CUSTOMER_TYPE3 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP AS CURRENT_MEMBERSHIP,
    NULL AS PREVIOUS_MEMBERSHIP,
    SEGMENT
FROM STG_CUSTOMERS_INITIAL;


/* =====================================================================
   TASK 13 — VALIDATE INITIAL TYPE 3 RECORDS
   ===================================================================== */

SELECT
    COUNT(*) AS TYPE3_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE3;


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CURRENT_MEMBERSHIP AS OLD_MEMBERSHIP,
    U.MEMBERSHIP AS NEW_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3 C
JOIN STG_CUSTOMER_UPDATES U
    ON C.CUSTOMER_ID = U.CUSTOMER_ID
WHERE C.CURRENT_MEMBERSHIP <> U.MEMBERSHIP
ORDER BY C.CUSTOMER_ID;

UPDATE DIM_CUSTOMER_TYPE3 C

SET
    PREVIOUS_MEMBERSHIP = C.CURRENT_MEMBERSHIP,
    CURRENT_MEMBERSHIP = U.MEMBERSHIP,
    CUSTOMER_NAME = U.CUSTOMER_NAME,
    CITY = U.CITY,
    STATE = U.STATE,
    SEGMENT = U.SEGMENT

FROM STG_CUSTOMER_UPDATES U

WHERE C.CUSTOMER_ID = U.CUSTOMER_ID
  AND C.CURRENT_MEMBERSHIP <> U.MEMBERSHIP;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
WHERE CUSTOMER_ID = 101;

SELECT
    COUNT(*) AS SCD_TYPE3_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE3;

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE6 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

INSERT INTO DIM_CUSTOMER_TYPE6 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP AS CURRENT_MEMBERSHIP,
    NULL AS PREVIOUS_MEMBERSHIP,
    MEMBERSHIP AS HISTORICAL_MEMBERSHIP,
    SEGMENT,
    DATE '2026-01-01' AS EFFECTIVE_DATE,
    DATE '9999-12-31' AS EXPIRY_DATE,
    TRUE AS IS_CURRENT
FROM STG_CUSTOMERS_INITIAL;


SELECT
    COUNT(*) AS TOTAL_TYPE6_RECORDS,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_TYPE6;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID;

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CURRENT_MEMBERSHIP AS OLD_MEMBERSHIP,
    U.MEMBERSHIP AS NEW_MEMBERSHIP,
    U.EFFECTIVE_DATE
FROM DIM_CUSTOMER_TYPE6 C
JOIN STG_CUSTOMER_UPDATES U
    ON C.CUSTOMER_ID = U.CUSTOMER_ID
WHERE C.IS_CURRENT = TRUE
  AND C.CURRENT_MEMBERSHIP <> U.MEMBERSHIP
ORDER BY C.CUSTOMER_ID;

UPDATE DIM_CUSTOMER_TYPE6 C

SET
    EXPIRY_DATE = DATEADD(
        DAY,
        -1,
        U.EFFECTIVE_DATE
    ),

    IS_CURRENT = FALSE

FROM STG_CUSTOMER_UPDATES U

WHERE C.CUSTOMER_ID = U.CUSTOMER_ID
  AND C.IS_CURRENT = TRUE

  AND C.CURRENT_MEMBERSHIP <> U.MEMBERSHIP;
  
INSERT INTO DIM_CUSTOMER_TYPE6 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    U.CUSTOMER_ID,
    U.CUSTOMER_NAME,
    U.CITY,
    U.STATE,
    U.MEMBERSHIP AS CURRENT_MEMBERSHIP,

    C.CURRENT_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,

    U.MEMBERSHIP AS HISTORICAL_MEMBERSHIP,

    U.SEGMENT,

    U.EFFECTIVE_DATE,

    DATE '9999-12-31',

    TRUE

FROM STG_CUSTOMER_UPDATES U

JOIN DIM_CUSTOMER_TYPE6 C
    ON U.CUSTOMER_ID = C.CUSTOMER_ID

WHERE C.IS_CURRENT = FALSE

  AND C.EXPIRY_DATE = DATEADD(
        DAY,
        -1,
        U.EFFECTIVE_DATE
      );

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
ORDER BY
    CUSTOMER_ID,
    EFFECTIVE_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 103
ORDER BY EFFECTIVE_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 104
ORDER BY EFFECTIVE_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 101
  AND DATE '2026-03-15'
      BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 101
  AND DATE '2026-04-15'
      BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    CITY,
    STATE,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 103
  AND DATE '2026-03-20'
      BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 104
  AND DATE '2026-04-05'
      BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

SELECT
    COUNT(*) AS SCD_TYPE3_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE3;

SELECT
    COUNT(*) AS SCD_TYPE6_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE6;

SELECT
    COUNT(*) AS SCD_TYPE6_CURRENT_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE;

SELECT
    COUNT(*) AS SCD_TYPE6_HISTORICAL_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = FALSE;

SELECT

    COUNT(*) AS SCD_TYPE6_RECORD_COUNT,

    COUNT_IF(IS_CURRENT = TRUE)
        AS SCD_TYPE6_CURRENT_RECORD_COUNT,

    COUNT_IF(IS_CURRENT = FALSE)
        AS SCD_TYPE6_HISTORICAL_RECORD_COUNT

FROM DIM_CUSTOMER_TYPE6;

SELECT
    CUSTOMER_ID,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_TYPE6
GROUP BY CUSTOMER_ID
HAVING COUNT_IF(IS_CURRENT = TRUE) <> 1;

SELECT
    CUSTOMER_ID,
    CUSTOMER_KEY,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
WHERE EFFECTIVE_DATE > EXPIRY_DATE;

SELECT
    CUSTOMER_ID,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE
  AND EXPIRY_DATE <> DATE '9999-12-31';

SELECT
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
ORDER BY
    CUSTOMER_ID,
    EFFECTIVE_DATE;

SELECT
    'Current Value' AS FEATURE,
    'YES' AS SCD_TYPE3,
    'YES' AS SCD_TYPE6

UNION ALL

SELECT
    'Previous Value',
    'YES',
    'YES'

UNION ALL

SELECT
    'Historical Rows',
    'NO',
    'YES'

UNION ALL

SELECT
    'Effective Date',
    'NO',
    'YES'

UNION ALL

SELECT
    'Expiry Date',
    'NO',
    'YES'

UNION ALL

SELECT
    'IS_CURRENT',
    'NO',
    'YES';

SELECT
    'TYPE 3' AS SCD_TYPE,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
WHERE CUSTOMER_ID = 101;

SELECT
    'TYPE 6' AS SCD_TYPE,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;

SELECT
    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_TYPE3)
        AS SCD_TYPE3_RECORD_COUNT,

    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_TYPE6)
        AS SCD_TYPE6_RECORD_COUNT,

    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_TYPE6
     WHERE IS_CURRENT = TRUE)
        AS SCD_TYPE6_CURRENT_RECORD_COUNT,

    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_TYPE6
     WHERE IS_CURRENT = FALSE)
        AS SCD_TYPE6_HISTORICAL_RECORD_COUNT;