CREATE OR REPLACE DATABASE FINANCIAL_GATEWAY_DB;

USE DATABASE FINANCIAL_GATEWAY_DB;

CREATE OR REPLACE SCHEMA PAYMENT_CORE;

USE SCHEMA PAYMENT_CORE;

CREATE OR REPLACE TABLE BRONZE_PAYMENT_PAYLOADS (
    INGEST_ID INTEGER AUTOINCREMENT,
    RAW_PAYLOAD VARIANT,
    RECORDED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW_PAYMENT_QUEUE (
    RAW_RECORD_TEXT VARCHAR
);

INSERT INTO RAW_PAYMENT_QUEUE (RAW_RECORD_TEXT)
VALUES
('{"txn_id":"TXN-901","txn_time":"2026-07-10T10:00:00Z","merchant_id":301,"merchant_name":"TechZone","card_number":"4111222233334444","amount":50000.00,"fee_pct":2.5,"status":"APPROVED"}'),
('{"txn_id":"TXN-902","txn_time":"2026-07-10T10:15:00Z","merchant_id":302,"merchant_name":"StyleHub","card_number":"5500111122223333","amount":12000.00,"fee_pct":3.0,"status":"APPROVED"}'),
('{"txn_id":"TXN-903","txn_time":"2026-07-10T11:00:00Z","merchant_id":301,"merchant_name":"TechZone","card_number":"4111222233334444","amount":25000.00,"fee_pct":2.5,"status":"PENDING"}'),
('{"txn_id":"TXN-904","txn_time":"2026-07-10T11:30:00Z","merchant_id":303,"merchant_name":"FreshMart","card_number":"4000111122223333","amount":8500.00,"fee_pct":1.8,"status":"APPROVED"}'),
('{"txn_id":"TXN-905","txn_time":"2026-07-10T12:00:00Z","merchant_id":302,"merchant_name":"StyleHub","card_number":"5500111122223333","amount":45000.00,"fee_pct":3.0,"status":"DECLINED"}'),
('{"txn_id":"TXN-906","txn_time":"2026-07-10T12:30:00Z","merchant_id":301,"merchant_name":"TechZone","card_number":"4111222233334444","amount":150000.00,"fee_pct":2.5,"status":"APPROVED"}'),
('{"txn_id":"TXN-907","txn_time":"2026-07-10T13:00:00Z","merchant_id":303,"merchant_name":"FreshMart","card_number":"4000111122223333","amount":3200.00,"fee_pct":1.8,"status":"APPROVED"}'),
('{"txn_id":"TXN-908","txn_time":"2026-07-10T13:15:00Z","merchant_id":302,"merchant_name":"StyleHub","card_number":"5500111122223333","amount":67000.00,"fee_pct":3.0,"status":"PENDING"}');

INSERT INTO BRONZE_PAYMENT_PAYLOADS (
    RAW_PAYLOAD
)
SELECT
    TRY_PARSE_JSON(RAW_RECORD_TEXT)
FROM RAW_PAYMENT_QUEUE
WHERE TRY_PARSE_JSON(RAW_RECORD_TEXT) IS NOT NULL;

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS_CT
FROM BRONZE_PAYMENT_PAYLOADS;

SELECT
    RAW_PAYLOAD:txn_id::VARCHAR AS TXN_ID,
    RAW_PAYLOAD:txn_time::TIMESTAMP_TZ AS TXN_TIME,
    RAW_PAYLOAD:merchant_id::INTEGER AS MERCHANT_ID,
    RAW_PAYLOAD:merchant_name::VARCHAR AS MERCHANT_NAME,
    RAW_PAYLOAD:amount::NUMBER(18,2) AS AMOUNT,
    RAW_PAYLOAD:fee_pct::NUMBER(10,2) AS FEE_PCT,
    RAW_PAYLOAD:status::VARCHAR AS STATUS
FROM BRONZE_PAYMENT_PAYLOADS
ORDER BY TXN_ID;

CREATE OR REPLACE TABLE SILVER_CLEANED_TRANSACTIONS (
    TXN_ID VARCHAR(50),
    TXN_TIME TIMESTAMP_TZ,
    MERCHANT_ID INTEGER,
    MERCHANT_NAME VARCHAR(100),
    MASKED_CARD VARCHAR(30),
    GROSS_AMOUNT NUMBER(18,2),
    FEE_PCT NUMBER(10,2),
    PROCESSING_FEE NUMBER(18,2),
    NET_SETTLEMENT_AMOUNT NUMBER(18,2),
    STATUS VARCHAR(30)
);

INSERT INTO SILVER_CLEANED_TRANSACTIONS (
    TXN_ID,
    TXN_TIME,
    MERCHANT_ID,
    MERCHANT_NAME,
    MASKED_CARD,
    GROSS_AMOUNT,
    FEE_PCT,
    PROCESSING_FEE,
    NET_SETTLEMENT_AMOUNT,
    STATUS
)
SELECT
    RAW_PAYLOAD:txn_id::VARCHAR,
    RAW_PAYLOAD:txn_time::TIMESTAMP_TZ,
    RAW_PAYLOAD:merchant_id::INTEGER,
    RAW_PAYLOAD:merchant_name::VARCHAR,
    'XXXX-XXXX-XXXX-' || RIGHT(RAW_PAYLOAD:card_number::VARCHAR, 4),
    RAW_PAYLOAD:amount::NUMBER(18,2),
    RAW_PAYLOAD:fee_pct::NUMBER(10,2),
    ROUND(
        RAW_PAYLOAD:amount::NUMBER(18,2)
        * (RAW_PAYLOAD:fee_pct::NUMBER(10,2) / 100),
        2
    ),
    ROUND(
        RAW_PAYLOAD:amount::NUMBER(18,2)
        -
        (
            RAW_PAYLOAD:amount::NUMBER(18,2)
            * (RAW_PAYLOAD:fee_pct::NUMBER(10,2) / 100)
        ),
        2
    ),
    RAW_PAYLOAD:status::VARCHAR
FROM BRONZE_PAYMENT_PAYLOADS;

SELECT
    TXN_ID,
    MERCHANT_ID,
    MERCHANT_NAME,
    MASKED_CARD,
    GROSS_AMOUNT,
    PROCESSING_FEE,
    NET_SETTLEMENT_AMOUNT,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
ORDER BY TXN_ID;

CREATE OR REPLACE TABLE GOLD_MERCHANT_SETTLEMENTS (
    MERCHANT_ID INTEGER,
    MERCHANT_NAME VARCHAR(100),
    TOTAL_APPROVED_GROSS NUMBER(18,2),
    TOTAL_GATEWAY_FEES NUMBER(18,2),
    TOTAL_NET_PAYOUT NUMBER(18,2),
    APPROVED_COUNT INTEGER
);

INSERT INTO GOLD_MERCHANT_SETTLEMENTS (
    MERCHANT_ID,
    MERCHANT_NAME,
    TOTAL_APPROVED_GROSS,
    TOTAL_GATEWAY_FEES,
    TOTAL_NET_PAYOUT,
    APPROVED_COUNT
)
SELECT
    MERCHANT_ID,
    MERCHANT_NAME,
    SUM(GROSS_AMOUNT),
    SUM(PROCESSING_FEE),
    SUM(NET_SETTLEMENT_AMOUNT),
    COUNT(*)
FROM SILVER_CLEANED_TRANSACTIONS
WHERE STATUS = 'APPROVED'
GROUP BY
    MERCHANT_ID,
    MERCHANT_NAME
ORDER BY MERCHANT_ID;

SELECT
    MERCHANT_ID,
    MERCHANT_NAME,
    TOTAL_APPROVED_GROSS,
    TOTAL_GATEWAY_FEES,
    TOTAL_NET_PAYOUT,
    APPROVED_COUNT
FROM GOLD_MERCHANT_SETTLEMENTS
ORDER BY MERCHANT_ID;

SET BEFORE_CORRUPTION_TIME = CURRENT_TIMESTAMP();

SELECT
    TXN_ID,
    MERCHANT_NAME,
    GROSS_AMOUNT,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
  AND STATUS = 'APPROVED'
ORDER BY TXN_ID;

UPDATE SILVER_CLEANED_TRANSACTIONS
SET STATUS = 'REFUNDED'
WHERE MERCHANT_NAME = 'TechZone'
  AND STATUS = 'APPROVED';

SELECT
    TXN_ID,
    MERCHANT_NAME,
    GROSS_AMOUNT,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
ORDER BY TXN_ID;

SELECT
    TXN_ID,
    MERCHANT_NAME,
    GROSS_AMOUNT,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
AT (TIMESTAMP => $BEFORE_CORRUPTION_TIME)
WHERE MERCHANT_NAME = 'TechZone'
  AND STATUS = 'APPROVED'
ORDER BY TXN_ID;

UPDATE SILVER_CLEANED_TRANSACTIONS AS CURRENT_DATA
SET STATUS = ORIGINAL_DATA.STATUS
FROM (
    SELECT
        TXN_ID,
        STATUS
    FROM SILVER_CLEANED_TRANSACTIONS
    AT (TIMESTAMP => $BEFORE_CORRUPTION_TIME)
) AS ORIGINAL_DATA
WHERE CURRENT_DATA.TXN_ID = ORIGINAL_DATA.TXN_ID
  AND CURRENT_DATA.MERCHANT_NAME = 'TechZone';

SELECT
    MERCHANT_NAME,
    COUNT_IF(STATUS = 'APPROVED') AS APPROVED_COUNT,
    COUNT_IF(STATUS = 'REFUNDED') AS REFUNDED_COUNT
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
GROUP BY MERCHANT_NAME;

SELECT
    TXN_ID,
    MERCHANT_NAME,
    GROSS_AMOUNT,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
ORDER BY TXN_ID;

WITH BRONZE_TOTAL AS (
    SELECT
        SUM(RAW_PAYLOAD:amount::NUMBER(18,2)) AS BRONZE_GROSS_SUM
    FROM BRONZE_PAYMENT_PAYLOADS
),
SILVER_TOTAL AS (
    SELECT
        SUM(GROSS_AMOUNT) AS SILVER_GROSS_SUM
    FROM SILVER_CLEANED_TRANSACTIONS
),
GOLD_TOTAL AS (
    SELECT
        SUM(TOTAL_APPROVED_GROSS) AS GOLD_GROSS_SUM
    FROM GOLD_MERCHANT_SETTLEMENTS
)
SELECT
    B.BRONZE_GROSS_SUM,
    S.SILVER_GROSS_SUM,
    G.GOLD_GROSS_SUM,
    CASE
        WHEN B.BRONZE_GROSS_SUM = S.SILVER_GROSS_SUM
         AND G.GOLD_GROSS_SUM <= S.SILVER_GROSS_SUM
        THEN TRUE
        ELSE FALSE
    END AS DATA_MATCH_FLAG
FROM BRONZE_TOTAL B
CROSS JOIN SILVER_TOTAL S
CROSS JOIN GOLD_TOTAL G;

SELECT
    'BRONZE' AS LAYER,
    SUM(RAW_PAYLOAD:amount::NUMBER(18,2)) AS GROSS_TOTAL
FROM BRONZE_PAYMENT_PAYLOADS

UNION ALL

SELECT
    'SILVER' AS LAYER,
    SUM(GROSS_AMOUNT) AS GROSS_TOTAL
FROM SILVER_CLEANED_TRANSACTIONS

UNION ALL

SELECT
    'GOLD' AS LAYER,
    SUM(TOTAL_APPROVED_GROSS) AS GROSS_TOTAL
FROM GOLD_MERCHANT_SETTLEMENTS;