CREATE OR REPLACE DATABASE HEALTHCARE_DW;

USE DATABASE HEALTHCARE_DW;

CREATE OR REPLACE SCHEMA SCHEMA_COMPARE_LAB;

USE SCHEMA SCHEMA_COMPARE_LAB;


CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;


CREATE OR REPLACE STAGE HEALTHCARE_STAGE
FILE_FORMAT = CSV_FORMAT;


LIST @HEALTHCARE_STAGE;


CREATE OR REPLACE TABLE STG_HOSPITAL_HIERARCHY (
    HOSPITAL_ID NUMBER,
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    NETWORK_ID NUMBER,
    NETWORK_NAME VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);


CREATE OR REPLACE TABLE STG_TREATMENT_HIERARCHY (
    TREATMENT_ID NUMBER,
    TREATMENT_NAME VARCHAR(100),
    DIAGNOSIS_GROUP_ID VARCHAR(50),
    DIAGNOSIS_GROUP_NAME VARCHAR(50),
    STANDARD_COST NUMBER(12,2)
);


CREATE OR REPLACE TABLE STG_PATIENTS (
    PATIENT_ID NUMBER,
    PATIENT_NAME VARCHAR(100),
    GENDER VARCHAR(20),
    AGE NUMBER,
    CITY VARCHAR(50)
);


CREATE OR REPLACE TABLE STG_INSURANCE_CLAIMS (
    CLAIM_ID VARCHAR(50),
    CLAIM_DATE DATE,
    PATIENT_ID NUMBER,
    HOSPITAL_ID NUMBER,
    TREATMENT_ID NUMBER,
    CLAIMED_AMOUNT NUMBER(12,2),
    APPROVED_AMOUNT NUMBER(12,2)
);


COPY INTO STG_HOSPITAL_HIERARCHY
FROM @HEALTHCARE_STAGE/hospital_hierarchy.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO STG_TREATMENT_HIERARCHY
FROM @HEALTHCARE_STAGE/treatment_hierarchy.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO STG_PATIENTS
FROM @HEALTHCARE_STAGE/patients.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO STG_INSURANCE_CLAIMS
FROM @HEALTHCARE_STAGE/insurance_claims.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


CREATE OR REPLACE TABLE STAR_DIM_HOSPITAL (
    HOSPITAL_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    HOSPITAL_ID NUMBER,
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    NETWORK_NAME VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);


CREATE OR REPLACE TABLE STAR_DIM_TREATMENT (
    TREATMENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID NUMBER,
    TREATMENT_NAME VARCHAR(100),
    DIAGNOSIS_GROUP_NAME VARCHAR(50),
    STANDARD_COST NUMBER(12,2)
);


INSERT INTO STAR_DIM_HOSPITAL (
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    NETWORK_NAME,
    NETWORK_DIRECTOR
)
SELECT
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    NETWORK_NAME,
    NETWORK_DIRECTOR
FROM STG_HOSPITAL_HIERARCHY;


INSERT INTO STAR_DIM_TREATMENT (
    TREATMENT_ID,
    TREATMENT_NAME,
    DIAGNOSIS_GROUP_NAME,
    STANDARD_COST
)
SELECT
    TREATMENT_ID,
    TREATMENT_NAME,
    DIAGNOSIS_GROUP_NAME,
    STANDARD_COST
FROM STG_TREATMENT_HIERARCHY;


CREATE OR REPLACE TABLE STAR_FACT_CLAIMS (
    CLAIM_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CLAIM_ID VARCHAR(50),
    CLAIM_DATE DATE,
    PATIENT_ID NUMBER,
    HOSPITAL_KEY NUMBER,
    TREATMENT_KEY NUMBER,
    CLAIMED_AMOUNT NUMBER(12,2),
    APPROVED_AMOUNT NUMBER(12,2),
    FOREIGN KEY (HOSPITAL_KEY)
        REFERENCES STAR_DIM_HOSPITAL(HOSPITAL_KEY),
    FOREIGN KEY (TREATMENT_KEY)
        REFERENCES STAR_DIM_TREATMENT(TREATMENT_KEY)
);


INSERT INTO STAR_FACT_CLAIMS (
    CLAIM_ID,
    CLAIM_DATE,
    PATIENT_ID,
    HOSPITAL_KEY,
    TREATMENT_KEY,
    CLAIMED_AMOUNT,
    APPROVED_AMOUNT
)
SELECT
    c.CLAIM_ID,
    c.CLAIM_DATE,
    c.PATIENT_ID,
    h.HOSPITAL_KEY,
    t.TREATMENT_KEY,
    c.CLAIMED_AMOUNT,
    c.APPROVED_AMOUNT
FROM STG_INSURANCE_CLAIMS c
JOIN STAR_DIM_HOSPITAL h
    ON c.HOSPITAL_ID = h.HOSPITAL_ID
JOIN STAR_DIM_TREATMENT t
    ON c.TREATMENT_ID = t.TREATMENT_ID;


CREATE OR REPLACE TABLE SNOW_DIM_NETWORK (
    NETWORK_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    NETWORK_ID NUMBER,
    NETWORK_NAME VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);


CREATE OR REPLACE TABLE SNOW_DIM_HOSPITAL (
    HOSPITAL_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    HOSPITAL_ID NUMBER,
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    NETWORK_KEY NUMBER,
    FOREIGN KEY (NETWORK_KEY)
        REFERENCES SNOW_DIM_NETWORK(NETWORK_KEY)
);


CREATE OR REPLACE TABLE SNOW_DIM_DIAGNOSIS_GROUP (
    DIAGNOSIS_GROUP_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    DIAGNOSIS_GROUP_ID VARCHAR(50),
    DIAGNOSIS_GROUP_NAME VARCHAR(50)
);


CREATE OR REPLACE TABLE SNOW_DIM_TREATMENT (
    TREATMENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID NUMBER,
    TREATMENT_NAME VARCHAR(100),
    STANDARD_COST NUMBER(12,2),
    DIAGNOSIS_GROUP_KEY NUMBER,
    FOREIGN KEY (DIAGNOSIS_GROUP_KEY)
        REFERENCES SNOW_DIM_DIAGNOSIS_GROUP(DIAGNOSIS_GROUP_KEY)
);


INSERT INTO SNOW_DIM_NETWORK (
    NETWORK_ID,
    NETWORK_NAME,
    NETWORK_DIRECTOR
)
SELECT DISTINCT
    NETWORK_ID,
    NETWORK_NAME,
    NETWORK_DIRECTOR
FROM STG_HOSPITAL_HIERARCHY;


INSERT INTO SNOW_DIM_HOSPITAL (
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    NETWORK_KEY
)
SELECT
    h.HOSPITAL_ID,
    h.HOSPITAL_NAME,
    h.CITY,
    h.STATE,
    n.NETWORK_KEY
FROM STG_HOSPITAL_HIERARCHY h
JOIN SNOW_DIM_NETWORK n
    ON h.NETWORK_ID = n.NETWORK_ID;


INSERT INTO SNOW_DIM_DIAGNOSIS_GROUP (
    DIAGNOSIS_GROUP_ID,
    DIAGNOSIS_GROUP_NAME
)
SELECT DISTINCT
    DIAGNOSIS_GROUP_ID,
    DIAGNOSIS_GROUP_NAME
FROM STG_TREATMENT_HIERARCHY;


INSERT INTO SNOW_DIM_TREATMENT (
    TREATMENT_ID,
    TREATMENT_NAME,
    STANDARD_COST,
    DIAGNOSIS_GROUP_KEY
)
SELECT
    t.TREATMENT_ID,
    t.TREATMENT_NAME,
    t.STANDARD_COST,
    d.DIAGNOSIS_GROUP_KEY
FROM STG_TREATMENT_HIERARCHY t
JOIN SNOW_DIM_DIAGNOSIS_GROUP d
    ON TRIM(LOWER(t.DIAGNOSIS_GROUP_ID))
       = TRIM(LOWER(d.DIAGNOSIS_GROUP_ID));


CREATE OR REPLACE TABLE SNOW_FACT_CLAIMS (
    CLAIM_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CLAIM_ID VARCHAR(50),
    CLAIM_DATE DATE,
    PATIENT_ID NUMBER,
    HOSPITAL_KEY NUMBER,
    TREATMENT_KEY NUMBER,
    CLAIMED_AMOUNT NUMBER(12,2),
    APPROVED_AMOUNT NUMBER(12,2),
    FOREIGN KEY (HOSPITAL_KEY)
        REFERENCES SNOW_DIM_HOSPITAL(HOSPITAL_KEY),
    FOREIGN KEY (TREATMENT_KEY)
        REFERENCES SNOW_DIM_TREATMENT(TREATMENT_KEY)
);


INSERT INTO SNOW_FACT_CLAIMS (
    CLAIM_ID,
    CLAIM_DATE,
    PATIENT_ID,
    HOSPITAL_KEY,
    TREATMENT_KEY,
    CLAIMED_AMOUNT,
    APPROVED_AMOUNT
)
SELECT
    c.CLAIM_ID,
    c.CLAIM_DATE,
    c.PATIENT_ID,
    h.HOSPITAL_KEY,
    t.TREATMENT_KEY,
    c.CLAIMED_AMOUNT,
    c.APPROVED_AMOUNT
FROM STG_INSURANCE_CLAIMS c
JOIN SNOW_DIM_HOSPITAL h
    ON c.HOSPITAL_ID = h.HOSPITAL_ID
JOIN SNOW_DIM_TREATMENT t
    ON c.TREATMENT_ID = t.TREATMENT_ID;


SELECT
    DIAGNOSIS_GROUP_NAME,
    SUM(CLAIMED_AMOUNT) AS TOTAL_CLAIMED_AMOUNT,
    SUM(APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS f
JOIN STAR_DIM_TREATMENT t
    ON f.TREATMENT_KEY = t.TREATMENT_KEY
GROUP BY
    DIAGNOSIS_GROUP_NAME
ORDER BY
    DIAGNOSIS_GROUP_NAME;


SELECT
    d.DIAGNOSIS_GROUP_NAME,
    SUM(f.CLAIMED_AMOUNT) AS TOTAL_CLAIMED_AMOUNT,
    SUM(f.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS f
JOIN SNOW_DIM_TREATMENT t
    ON f.TREATMENT_KEY = t.TREATMENT_KEY
JOIN SNOW_DIM_DIAGNOSIS_GROUP d
    ON t.DIAGNOSIS_GROUP_KEY = d.DIAGNOSIS_GROUP_KEY
GROUP BY
    d.DIAGNOSIS_GROUP_NAME
ORDER BY
    d.DIAGNOSIS_GROUP_NAME;


SELECT
    h.NETWORK_DIRECTOR,
    COUNT(f.CLAIM_ID) AS TOTAL_CLAIMS_HANDLED,
    SUM(f.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS f
JOIN STAR_DIM_HOSPITAL h
    ON f.HOSPITAL_KEY = h.HOSPITAL_KEY
GROUP BY
    h.NETWORK_DIRECTOR
ORDER BY
    h.NETWORK_DIRECTOR;


SELECT
    n.NETWORK_DIRECTOR,
    COUNT(f.CLAIM_ID) AS TOTAL_CLAIMS_HANDLED,
    SUM(f.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS f
JOIN SNOW_DIM_HOSPITAL h
    ON f.HOSPITAL_KEY = h.HOSPITAL_KEY
JOIN SNOW_DIM_NETWORK n
    ON h.NETWORK_KEY = n.NETWORK_KEY
GROUP BY
    n.NETWORK_DIRECTOR
ORDER BY
    n.NETWORK_DIRECTOR;


SELECT
    HOSPITAL_ID,
    HOSPITAL_NAME,
    NETWORK_NAME,
    NETWORK_DIRECTOR
FROM STAR_DIM_HOSPITAL
WHERE NETWORK_NAME = 'Apollo Healthcare Group';


UPDATE STAR_DIM_HOSPITAL
SET NETWORK_DIRECTOR = 'Dr. Anand'
WHERE NETWORK_NAME = 'Apollo Healthcare Group'
  AND NETWORK_DIRECTOR = 'Dr. Ramesh';


SELECT
    COUNT(*) AS STAR_ROWS_UPDATED
FROM STAR_DIM_HOSPITAL
WHERE NETWORK_NAME = 'Apollo Healthcare Group'
  AND NETWORK_DIRECTOR = 'Dr. Anand';


UPDATE SNOW_DIM_NETWORK
SET NETWORK_DIRECTOR = 'Dr. Anand'
WHERE NETWORK_ID = 10
  AND NETWORK_DIRECTOR = 'Dr. Ramesh';


SELECT
    COUNT(*) AS SNOWFLAKE_ROWS_UPDATED
FROM SNOW_DIM_NETWORK
WHERE NETWORK_ID = 10
  AND NETWORK_DIRECTOR = 'Dr. Anand';


SELECT
    'Star Schema' AS SCHEMA_TYPE,
    'STAR_DIM_HOSPITAL' AS UPDATED_TABLE,
    COUNT(*) AS ROWS_UPDATED,
    'Higher (Multiple rows)' AS MAINTENANCE_EFFORT
FROM STAR_DIM_HOSPITAL
WHERE NETWORK_NAME = 'Apollo Healthcare Group'
  AND NETWORK_DIRECTOR = 'Dr. Anand'

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_NETWORK',
    COUNT(*),
    'Lower (Single row)'
FROM SNOW_DIM_NETWORK
WHERE NETWORK_ID = 10
  AND NETWORK_DIRECTOR = 'Dr. Anand';


SELECT
    'Star Schema' AS SCHEMA_TYPE,
    'STAR_DIM_HOSPITAL' AS TABLE_NAME,
    COUNT(*) AS RECORD_COUNT
FROM STAR_DIM_HOSPITAL

UNION ALL

SELECT
    'Star Schema',
    'STAR_DIM_TREATMENT',
    COUNT(*)
FROM STAR_DIM_TREATMENT

UNION ALL

SELECT
    'Star Schema',
    'STAR_FACT_CLAIMS',
    COUNT(*)
FROM STAR_FACT_CLAIMS

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_NETWORK',
    COUNT(*)
FROM SNOW_DIM_NETWORK

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_HOSPITAL',
    COUNT(*)
FROM SNOW_DIM_HOSPITAL

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_DIAGNOSIS_GROUP',
    COUNT(*)
FROM SNOW_DIM_DIAGNOSIS_GROUP

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_TREATMENT',
    COUNT(*)
FROM SNOW_DIM_TREATMENT

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_FACT_CLAIMS',
    COUNT(*)
FROM SNOW_FACT_CLAIMS;


SELECT
    'Dimension Normalization Level' AS METRIC_FEATURE,
    'Denormalized (Flat)' AS STAR_SCHEMA,
    'Normalized (Hierarchical)' AS SNOWFLAKE_SCHEMA

UNION ALL

SELECT
    'Total Dimension Tables',
    '2 Tables',
    '4 Tables'

UNION ALL

SELECT
    'Joins for Specialty Claims',
    '1 Join',
    '2 Joins'

UNION ALL

SELECT
    'Data Redundancy',
    'Higher (Repeated network and diagnosis attributes)',
    'Lower (Normalized IDs)'

UNION ALL

SELECT
    'Query Simplicity',
    'High (Simple joins)',
    'Lower (Requires hierarchical joins)';