
CREATE OR REPLACE DATABASE PROJECT_19A_DB;

USE DATABASE PROJECT_19A_DB;

CREATE OR REPLACE SCHEMA ECOMMERCE_SCHEMA;

USE SCHEMA ECOMMERCE_SCHEMA;



CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null')
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

CREATE OR REPLACE STAGE ECOMMERCE_STAGE
FILE_FORMAT = CSV_FORMAT;



CREATE OR REPLACE TABLE RAW_ORDERS (
    ORDER_ID VARCHAR(20),
    ORDER_DATE DATE,
    USER_ID VARCHAR(20),
    STORE_ID VARCHAR(20),
    AMOUNT NUMBER(12,2),
    TAX NUMBER(12,2),
    PAYMENT_METHOD VARCHAR(50),
    SHIPPING_OPTION VARCHAR(50),
    GIFT_WRAP_FLAG VARCHAR(5)
);



CREATE OR REPLACE TABLE RAW_INVENTORY (
    SNAPSHOT_DATE DATE,
    STORE_ID VARCHAR(20),
    PRODUCT_ID VARCHAR(20),
    QTY_ON_HAND NUMBER(12,0),
    UNIT_COST NUMBER(12,2)
);



CREATE OR REPLACE TABLE RAW_FULFILLMENT (
    ORDER_ID VARCHAR(20),
    ORDER_DATE DATE,
    PICK_DATE DATE,
    SHIP_DATE DATE,
    DELIVERY_DATE DATE
);




COPY INTO RAW_ORDERS
FROM @ECOMMERCE_STAGE/raw_orders.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_INVENTORY
FROM @ECOMMERCE_STAGE/raw_inventory.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_FULFILLMENT
FROM @ECOMMERCE_STAGE/raw_fulfillment.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


-- ============================================================================
-- 7. CHECK RAW DATA
-- ============================================================================

SELECT * FROM RAW_ORDERS ORDER BY ORDER_ID;

SELECT * FROM RAW_INVENTORY
ORDER BY SNAPSHOT_DATE, STORE_ID, PRODUCT_ID;

SELECT * FROM RAW_FULFILLMENT
ORDER BY ORDER_ID;


-- ============================================================================
-- TASK 1: JUNK DIMENSION
-- DIM_ORDER_INDICATORS
-- ============================================================================

CREATE OR REPLACE TABLE DIM_ORDER_INDICATORS (
    INDICATOR_SK NUMBER AUTOINCREMENT,
    PAYMENT_METHOD VARCHAR(50),
    SHIPPING_OPTION VARCHAR(50),
    GIFT_WRAP_FLAG VARCHAR(5)
);


INSERT INTO DIM_ORDER_INDICATORS
(
    PAYMENT_METHOD,
    SHIPPING_OPTION,
    GIFT_WRAP_FLAG
)
SELECT DISTINCT
    PAYMENT_METHOD,
    SHIPPING_OPTION,
    GIFT_WRAP_FLAG
FROM RAW_ORDERS
ORDER BY
    CASE
        WHEN PAYMENT_METHOD = 'Credit'
             AND SHIPPING_OPTION = 'Express'
             AND GIFT_WRAP_FLAG = 'Y' THEN 1

        WHEN PAYMENT_METHOD = 'UPI'
             AND SHIPPING_OPTION = 'Standard'
             AND GIFT_WRAP_FLAG = 'N' THEN 2

        WHEN PAYMENT_METHOD = 'Credit'
             AND SHIPPING_OPTION = 'Express'
             AND GIFT_WRAP_FLAG = 'N' THEN 3

        WHEN PAYMENT_METHOD = 'NetBanking'
             AND SHIPPING_OPTION = 'Standard'
             AND GIFT_WRAP_FLAG = 'Y' THEN 4

        WHEN PAYMENT_METHOD = 'UPI'
             AND SHIPPING_OPTION = 'Express'
             AND GIFT_WRAP_FLAG = 'Y' THEN 5

        WHEN PAYMENT_METHOD = 'Credit'
             AND SHIPPING_OPTION = 'Standard'
             AND GIFT_WRAP_FLAG = 'N' THEN 6

        ELSE 99
    END;


-- CHECK JUNK DIMENSION

SELECT *
FROM DIM_ORDER_INDICATORS
ORDER BY INDICATOR_SK;


-- ============================================================================
-- TASK 2: TRANSACTION FACT TABLE
-- FACT_SALES_TRANSACTIONS
-- ============================================================================

CREATE OR REPLACE TABLE FACT_SALES_TRANSACTIONS (
    ORDER_ID VARCHAR(20),
    ORDER_DATE DATE,
    USER_ID VARCHAR(20),
    STORE_ID VARCHAR(20),
    INDICATOR_SK NUMBER,
    AMOUNT NUMBER(12,2),
    TAX NUMBER(12,2)
);


INSERT INTO FACT_SALES_TRANSACTIONS
(
    ORDER_ID,
    ORDER_DATE,
    USER_ID,
    STORE_ID,
    INDICATOR_SK,
    AMOUNT,
    TAX
)
SELECT
    r.ORDER_ID,
    r.ORDER_DATE,
    r.USER_ID,
    r.STORE_ID,
    d.INDICATOR_SK,
    r.AMOUNT,
    r.TAX
FROM RAW_ORDERS r
JOIN DIM_ORDER_INDICATORS d
    ON r.PAYMENT_METHOD = d.PAYMENT_METHOD
   AND r.SHIPPING_OPTION = d.SHIPPING_OPTION
   AND r.GIFT_WRAP_FLAG = d.GIFT_WRAP_FLAG;


-- CHECK TRANSACTION FACT

SELECT
    ORDER_ID,
    INDICATOR_SK,
    AMOUNT
FROM FACT_SALES_TRANSACTIONS
ORDER BY ORDER_ID;


-- ============================================================================
-- TASK 3: PERIODIC SNAPSHOT FACT TABLE
-- FACT_INVENTORY_SNAPSHOT
-- ============================================================================

CREATE OR REPLACE TABLE FACT_INVENTORY_SNAPSHOT (
    SNAPSHOT_DATE DATE,
    STORE_ID VARCHAR(20),
    TOTAL_UNITS_HELD NUMBER(12,0),
    TOTAL_INVENTORY_VAL NUMBER(14,2)
);


INSERT INTO FACT_INVENTORY_SNAPSHOT
(
    SNAPSHOT_DATE,
    STORE_ID,
    TOTAL_UNITS_HELD,
    TOTAL_INVENTORY_VAL
)
SELECT
    SNAPSHOT_DATE,
    STORE_ID,
    SUM(QTY_ON_HAND) AS TOTAL_UNITS_HELD,
    SUM(QTY_ON_HAND * UNIT_COST) AS TOTAL_INVENTORY_VAL
FROM RAW_INVENTORY
GROUP BY
    SNAPSHOT_DATE,
    STORE_ID;


-- CHECK PERIODIC SNAPSHOT

SELECT
    SNAPSHOT_DATE,
    STORE_ID,
    TOTAL_UNITS_HELD,
    TOTAL_INVENTORY_VAL
FROM FACT_INVENTORY_SNAPSHOT
ORDER BY
    SNAPSHOT_DATE,
    STORE_ID;


-- ============================================================================
-- TASK 4: ACCUMULATING SNAPSHOT FACT TABLE
-- FACT_ORDER_FULFILLMENT
-- ============================================================================

CREATE OR REPLACE TABLE FACT_ORDER_FULFILLMENT (
    ORDER_ID VARCHAR(20),
    ORDER_DATE DATE,
    PICK_DATE DATE,
    SHIP_DATE DATE,
    DELIVERY_DATE DATE,
    PICK_LAG_DAYS NUMBER,
    SHIP_LAG_DAYS NUMBER,
    DELIVERY_LAG_DAYS NUMBER,
    TOTAL_FULFILLMENT_DAYS NUMBER
);


INSERT INTO FACT_ORDER_FULFILLMENT
(
    ORDER_ID,
    ORDER_DATE,
    PICK_DATE,
    SHIP_DATE,
    DELIVERY_DATE,
    PICK_LAG_DAYS,
    SHIP_LAG_DAYS,
    DELIVERY_LAG_DAYS,
    TOTAL_FULFILLMENT_DAYS
)
SELECT
    ORDER_ID,
    ORDER_DATE,
    PICK_DATE,
    SHIP_DATE,
    DELIVERY_DATE,

    DATEDIFF(
        DAY,
        ORDER_DATE,
        PICK_DATE
    ) AS PICK_LAG_DAYS,

    CASE
        WHEN SHIP_DATE IS NOT NULL
        THEN DATEDIFF(
            DAY,
            PICK_DATE,
            SHIP_DATE
        )
        ELSE NULL
    END AS SHIP_LAG_DAYS,

    CASE
        WHEN DELIVERY_DATE IS NOT NULL
        THEN DATEDIFF(
            DAY,
            SHIP_DATE,
            DELIVERY_DATE
        )
        ELSE NULL
    END AS DELIVERY_LAG_DAYS,

    CASE
        WHEN DELIVERY_DATE IS NOT NULL
        THEN DATEDIFF(
            DAY,
            ORDER_DATE,
            DELIVERY_DATE
        )
        ELSE NULL
    END AS TOTAL_FULFILLMENT_DAYS

FROM RAW_FULFILLMENT;


-- CHECK ACCUMULATING SNAPSHOT

SELECT
    ORDER_ID,
    PICK_LAG_DAYS,
    SHIP_LAG_DAYS,
    DELIVERY_LAG_DAYS,
    TOTAL_FULFILLMENT_DAYS
FROM FACT_ORDER_FULFILLMENT
WHERE DELIVERY_LAG_DAYS IS NOT NULL
ORDER BY ORDER_ID;


-- ============================================================================
-- TASK 5: INCOMPLETE LIFECYCLE STATUS AUDITING
-- ============================================================================

SELECT
    ORDER_ID,
    ORDER_DATE,
    CASE

        WHEN PICK_DATE IS NULL
             THEN 'NOT_PICKED'

        WHEN PICK_DATE IS NOT NULL
             AND SHIP_DATE IS NULL
             THEN 'PICKED_NOT_SHIPPED'

        WHEN SHIP_DATE IS NOT NULL
             AND DELIVERY_DATE IS NULL
             THEN 'SHIPPED_NOT_DELIVERED'

        WHEN DELIVERY_DATE IS NOT NULL
             THEN 'DELIVERED'

        ELSE 'UNKNOWN'

    END AS CURRENT_STATUS

FROM FACT_ORDER_FULFILLMENT
WHERE DELIVERY_DATE IS NULL
ORDER BY ORDER_ID;


-- ============================================================================
-- TASK 6: REVENUE SUMMARY BY JUNK DIMENSION
-- ============================================================================

SELECT
    d.PAYMENT_METHOD,
    COUNT(f.ORDER_ID) AS TOTAL_ORDERS,
    SUM(f.AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES_TRANSACTIONS f
JOIN DIM_ORDER_INDICATORS d
    ON f.INDICATOR_SK = d.INDICATOR_SK
GROUP BY
    d.PAYMENT_METHOD
ORDER BY
    d.PAYMENT_METHOD;


-- ============================================================================
-- FINAL VALIDATION QUERIES
-- ============================================================================

-- TASK 1 OUTPUT

SELECT *
FROM DIM_ORDER_INDICATORS
ORDER BY INDICATOR_SK;


-- TASK 2 OUTPUT

SELECT
    ORDER_ID,
    INDICATOR_SK,
    AMOUNT
FROM FACT_SALES_TRANSACTIONS
ORDER BY ORDER_ID;


-- TASK 3 OUTPUT

SELECT
    SNAPSHOT_DATE,
    STORE_ID,
    TOTAL_UNITS_HELD,
    TOTAL_INVENTORY_VAL
FROM FACT_INVENTORY_SNAPSHOT
ORDER BY
    SNAPSHOT_DATE,
    STORE_ID;


-- TASK 4 OUTPUT

SELECT
    ORDER_ID,
    PICK_LAG_DAYS,
    SHIP_LAG_DAYS,
    DELIVERY_LAG_DAYS,
    TOTAL_FULFILLMENT_DAYS
FROM FACT_ORDER_FULFILLMENT
WHERE DELIVERY_LAG_DAYS IS NOT NULL
ORDER BY ORDER_ID;


-- TASK 5 OUTPUT

SELECT
    ORDER_ID,
    ORDER_DATE,
    CASE
        WHEN PICK_DATE IS NULL
            THEN 'NOT_PICKED'
        WHEN PICK_DATE IS NOT NULL
             AND SHIP_DATE IS NULL
            THEN 'PICKED_NOT_SHIPPED'
        WHEN SHIP_DATE IS NOT NULL
             AND DELIVERY_DATE IS NULL
            THEN 'SHIPPED_NOT_DELIVERED'
        WHEN DELIVERY_DATE IS NOT NULL
            THEN 'DELIVERED'
        ELSE 'UNKNOWN'
    END AS CURRENT_STATUS
FROM FACT_ORDER_FULFILLMENT
WHERE DELIVERY_DATE IS NULL
ORDER BY ORDER_ID;


-- TASK 6 OUTPUT

SELECT
    d.PAYMENT_METHOD,
    COUNT(f.ORDER_ID) AS TOTAL_ORDERS,
    SUM(f.AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES_TRANSACTIONS f
JOIN DIM_ORDER_INDICATORS d
    ON f.INDICATOR_SK = d.INDICATOR_SK
GROUP BY d.PAYMENT_METHOD
ORDER BY d.PAYMENT_METHOD;