CREATE OR REPLACE DATABASE HEALTHCARE_DB;

USE DATABASE HEALTHCARE_DB;

CREATE OR REPLACE SCHEMA PATIENT_ANALYTICS;

USE SCHEMA PATIENT_ANALYTICS;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE HEALTHCARE_STAGE
FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE TABLE RAW_DOCTOR_ROSTER (
    SHIFT_DATE DATE,
    DOCTOR_ID VARCHAR(20),
    DEPARTMENT_ID VARCHAR(20),
    SHIFT_TYPE VARCHAR(20)
);

COPY INTO RAW_DOCTOR_ROSTER
FROM @HEALTHCARE_STAGE
FILES = ('raw_doctor_roster.csv')
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE RAW_PATIENT_JOURNEY (
    ENCOUNTER_ID VARCHAR(20),
    PATIENT_ID VARCHAR(20),
    TRIAGE_DATE DATE,
    ADMISSION_DATE DATE,
    DISCHARGE_DATE DATE
);

COPY INTO RAW_PATIENT_JOURNEY
FROM @HEALTHCARE_STAGE
FILES = ('raw_patient_journey.csv')
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE RAW_TREATMENT_BILLS (
    CLAIM_ID VARCHAR(20),
    ENCOUNTER_ID VARCHAR(20),
    PATIENT_ID VARCHAR(20),
    PROCEDURE_COST NUMBER(12,2),
    INSURANCE_DISCOUNT_PCT NUMBER(5,2),
    COPAY_AMOUNT NUMBER(12,2)
);

COPY INTO RAW_TREATMENT_BILLS
FROM @HEALTHCARE_STAGE
FILES = ('raw_treatment_bills.csv')
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE FACTLESS_STAFF_COVERAGE (
    SHIFT_DATE DATE,
    DOCTOR_ID VARCHAR(20),
    DEPARTMENT_ID VARCHAR(20),
    SHIFT_TYPE VARCHAR(20)
);

INSERT INTO FACTLESS_STAFF_COVERAGE (
    SHIFT_DATE,
    DOCTOR_ID,
    DEPARTMENT_ID,
    SHIFT_TYPE
)
SELECT
    SHIFT_DATE,
    DOCTOR_ID,
    DEPARTMENT_ID,
    SHIFT_TYPE
FROM RAW_DOCTOR_ROSTER;

SELECT COUNT(*) AS TOTAL_ROSTER_ROWS
FROM FACTLESS_STAFF_COVERAGE;

SELECT
    DEPARTMENT_ID,
    COUNT_IF(SHIFT_TYPE = 'NIGHT') AS NIGHT_SHIFT_COUNT
FROM FACTLESS_STAFF_COVERAGE
WHERE SHIFT_DATE = '2026-08-20'
GROUP BY DEPARTMENT_ID
HAVING COUNT_IF(SHIFT_TYPE = 'NIGHT') = 0;

CREATE OR REPLACE TABLE FACT_PATIENT_ADMISSION_LIFECYCLE (
    ENCOUNTER_ID VARCHAR(20),
    PATIENT_ID VARCHAR(20),
    TRIAGE_DATE DATE,
    ADMISSION_DATE DATE,
    DISCHARGE_DATE DATE,
    TRIAGE_TO_ADMIT_DAYS INTEGER,
    LENGTH_OF_STAY_DAYS INTEGER
);

INSERT INTO FACT_PATIENT_ADMISSION_LIFECYCLE (
    ENCOUNTER_ID,
    PATIENT_ID,
    TRIAGE_DATE,
    ADMISSION_DATE,
    DISCHARGE_DATE,
    TRIAGE_TO_ADMIT_DAYS,
    LENGTH_OF_STAY_DAYS
)
SELECT
    ENCOUNTER_ID,
    PATIENT_ID,
    TRIAGE_DATE,
    ADMISSION_DATE,
    DISCHARGE_DATE,
    DATEDIFF(DAY, TRIAGE_DATE, ADMISSION_DATE),
    DATEDIFF(DAY, ADMISSION_DATE, DISCHARGE_DATE)
FROM RAW_PATIENT_JOURNEY
WHERE ADMISSION_DATE IS NOT NULL
AND DISCHARGE_DATE IS NOT NULL;

SELECT
    ENCOUNTER_ID,
    PATIENT_ID,
    TRIAGE_TO_ADMIT_DAYS,
    LENGTH_OF_STAY_DAYS
FROM FACT_PATIENT_ADMISSION_LIFECYCLE
ORDER BY ENCOUNTER_ID;

CREATE OR REPLACE TABLE FACT_TREATMENT_BILLING (
    CLAIM_ID VARCHAR(20),
    ENCOUNTER_ID VARCHAR(20),
    PATIENT_ID VARCHAR(20),
    PROCEDURE_COST NUMBER(12,2),
    INSURANCE_DISCOUNT_PCT NUMBER(5,2),
    COPAY_AMOUNT NUMBER(12,2),
    NET_CHARGE NUMBER(12,2)
);

INSERT INTO FACT_TREATMENT_BILLING (
    CLAIM_ID,
    ENCOUNTER_ID,
    PATIENT_ID,
    PROCEDURE_COST,
    INSURANCE_DISCOUNT_PCT,
    COPAY_AMOUNT,
    NET_CHARGE
)
SELECT
    CLAIM_ID,
    ENCOUNTER_ID,
    PATIENT_ID,
    PROCEDURE_COST,
    INSURANCE_DISCOUNT_PCT,
    COPAY_AMOUNT,
    (PROCEDURE_COST * (1 - INSURANCE_DISCOUNT_PCT)) - COPAY_AMOUNT
FROM RAW_TREATMENT_BILLS;

SELECT
    CLAIM_ID,
    ENCOUNTER_ID,
    PROCEDURE_COST,
    COPAY_AMOUNT,
    NET_CHARGE
FROM FACT_TREATMENT_BILLING
ORDER BY CLAIM_ID;

SELECT
    ENCOUNTER_ID,
    SUM(NET_CHARGE) AS TOTAL_NET_CHARGES,
    AVG(PROCEDURE_COST) AS AVG_PROCEDURE_COST
FROM FACT_TREATMENT_BILLING
GROUP BY ENCOUNTER_ID
ORDER BY ENCOUNTER_ID;

SELECT
    L.ENCOUNTER_ID,
    L.PATIENT_ID,
    'NO_CLAIMS_ISSUED' AS UNBILLED_STATUS
FROM FACT_PATIENT_ADMISSION_LIFECYCLE L
LEFT JOIN FACT_TREATMENT_BILLING B
    ON L.ENCOUNTER_ID = B.ENCOUNTER_ID
WHERE B.ENCOUNTER_ID IS NULL
ORDER BY L.ENCOUNTER_ID;

SELECT COUNT(*) AS TOTAL_ROSTER_ROWS
FROM FACTLESS_STAFF_COVERAGE;

SELECT
    COUNT(*) AS TOTAL_LIFECYCLE_ROWS
FROM FACT_PATIENT_ADMISSION_LIFECYCLE;

SELECT
    COUNT(*) AS TOTAL_BILLING_ROWS
FROM FACT_TREATMENT_BILLING;

SELECT
    COUNT(*) AS TOTAL_UNBILLED_ENCOUNTERS
FROM FACT_PATIENT_ADMISSION_LIFECYCLE L
LEFT JOIN FACT_TREATMENT_BILLING B
    ON L.ENCOUNTER_ID = B.ENCOUNTER_ID
WHERE B.ENCOUNTER_ID IS NULL;