USE WAREHOUSE SNOW_WH;

CREATE OR REPLACE DATABASE CUSTOMER_SCD_DW;

USE DATABASE CUSTOMER_SCD_DW;

CREATE OR REPLACE SCHEMA CUSTOMER_SCHEMA;

USE SCHEMA CUSTOMER_SCHEMA;

CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    TRIM_SPACE = TRUE
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE CUSTOMER_STAGE
    FILE_FORMAT = CUSTOMER_CSV_FORMAT;

LIST @CUSTOMER_STAGE;

CREATE OR REPLACE TABLE STG_CUSTOMERS_INITIAL (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);

CREATE OR REPLACE TABLE STG_CUSTOMER_UPDATES (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);

COPY INTO STG_CUSTOMERS_INITIAL
FROM @CUSTOMER_STAGE/customers_initial.csv
FILE_FORMAT = CUSTOMER_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO STG_CUSTOMER_UPDATES
FROM @CUSTOMER_STAGE/customer_updates.csv
FILE_FORMAT = CUSTOMER_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

SELECT COUNT(*) AS INITIAL_CUSTOMER_RECORDS
FROM STG_CUSTOMERS_INITIAL;

SELECT COUNT(*) AS UPDATE_RECORDS
FROM STG_CUSTOMER_UPDATES;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM STG_CUSTOMERS_INITIAL
ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE
FROM STG_CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID;

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE1 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);

INSERT INTO DIM_CUSTOMER_TYPE1 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM STG_CUSTOMERS_INITIAL;

SELECT COUNT(*) AS TYPE1_INITIAL_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE1;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE1
ORDER BY CUSTOMER_ID;

SELECT
    C.CUSTOMER_ID,
    C.CITY AS OLD_CITY,
    U.CITY AS NEW_CITY,
    C.STATE AS OLD_STATE,
    U.STATE AS NEW_STATE,
    C.MEMBERSHIP AS OLD_MEMBERSHIP,
    U.MEMBERSHIP AS NEW_MEMBERSHIP,
    C.SEGMENT AS OLD_SEGMENT,
    U.SEGMENT AS NEW_SEGMENT
FROM DIM_CUSTOMER_TYPE1 C
JOIN STG_CUSTOMER_UPDATES U
    ON C.CUSTOMER_ID = U.CUSTOMER_ID
WHERE
       NVL(C.CITY, '') <> NVL(U.CITY, '')
    OR NVL(C.STATE, '') <> NVL(U.STATE, '')
    OR NVL(C.MEMBERSHIP, '') <> NVL(U.MEMBERSHIP, '')
    OR NVL(C.SEGMENT, '') <> NVL(U.SEGMENT, '')
ORDER BY C.CUSTOMER_ID;

UPDATE DIM_CUSTOMER_TYPE1 C
SET
    CUSTOMER_NAME = U.CUSTOMER_NAME,
    CITY = U.CITY,
    STATE = U.STATE,
    MEMBERSHIP = U.MEMBERSHIP,
    SEGMENT = U.SEGMENT
FROM STG_CUSTOMER_UPDATES U
WHERE C.CUSTOMER_ID = U.CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE1
ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER_TYPE1
WHERE CUSTOMER_ID = 101;

SELECT *
FROM DIM_CUSTOMER_TYPE1
WHERE CUSTOMER_ID = 101
  AND CITY = 'Hyderabad'
  AND STATE = 'Telangana'
  AND MEMBERSHIP = 'Silver';

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE2 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

INSERT INTO DIM_CUSTOMER_TYPE2 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    DATE '2026-01-01',
    DATE '9999-12-31',
    TRUE
FROM STG_CUSTOMERS_INITIAL;

SELECT
    COUNT(*) AS TOTAL_TYPE2_RECORDS,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_TYPE2_RECORDS
FROM DIM_CUSTOMER_TYPE2;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID;

SELECT
    C.CUSTOMER_ID,
    C.CITY AS OLD_CITY,
    U.CITY AS NEW_CITY,
    C.STATE AS OLD_STATE,
    U.STATE AS NEW_STATE,
    C.MEMBERSHIP AS OLD_MEMBERSHIP,
    U.MEMBERSHIP AS NEW_MEMBERSHIP,
    C.SEGMENT AS OLD_SEGMENT,
    U.SEGMENT AS NEW_SEGMENT,
    U.EFFECTIVE_DATE
FROM DIM_CUSTOMER_TYPE2 C
JOIN STG_CUSTOMER_UPDATES U
    ON C.CUSTOMER_ID = U.CUSTOMER_ID
WHERE C.IS_CURRENT = TRUE
  AND (
       NVL(C.CITY, '') <> NVL(U.CITY, '')
    OR NVL(C.STATE, '') <> NVL(U.STATE, '')
    OR NVL(C.MEMBERSHIP, '') <> NVL(U.MEMBERSHIP, '')
    OR NVL(C.SEGMENT, '') <> NVL(U.SEGMENT, '')
  )
ORDER BY C.CUSTOMER_ID;

UPDATE DIM_CUSTOMER_TYPE2 C
SET
    EXPIRY_DATE = DATEADD(DAY, -1, U.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES U
WHERE C.CUSTOMER_ID = U.CUSTOMER_ID
  AND C.IS_CURRENT = TRUE
  AND (
       NVL(C.CITY, '') <> NVL(U.CITY, '')
    OR NVL(C.STATE, '') <> NVL(U.STATE, '')
    OR NVL(C.MEMBERSHIP, '') <> NVL(U.MEMBERSHIP, '')
    OR NVL(C.SEGMENT, '') <> NVL(U.SEGMENT, '')
  );

INSERT INTO DIM_CUSTOMER_TYPE2 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    U.CUSTOMER_ID,
    U.CUSTOMER_NAME,
    U.CITY,
    U.STATE,
    U.MEMBERSHIP,
    U.SEGMENT,
    U.EFFECTIVE_DATE,
    DATE '9999-12-31',
    TRUE
FROM STG_CUSTOMER_UPDATES U
WHERE EXISTS (
    SELECT 1
    FROM DIM_CUSTOMER_TYPE2 C
    WHERE C.CUSTOMER_ID = U.CUSTOMER_ID
      AND C.IS_CURRENT = FALSE
      AND C.EXPIRY_DATE = DATEADD(DAY, -1, U.EFFECTIVE_DATE)
);

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 103
ORDER BY EFFECTIVE_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 104
ORDER BY EFFECTIVE_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    MEMBERSHIP,
    CITY,
    STATE,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
  AND DATE '2026-03-15'
      BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    MEMBERSHIP,
    CITY,
    STATE,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
  AND DATE '2026-04-15'
      BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    MEMBERSHIP,
    CITY,
    STATE,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 103
  AND DATE '2026-03-20'
      BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    MEMBERSHIP,
    CITY,
    STATE,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 104
  AND DATE '2026-04-05'
      BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

SELECT COUNT(*) AS CURRENT_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = TRUE;

SELECT COUNT(*) AS HISTORICAL_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = FALSE;

SELECT COUNT(*) AS TOTAL_TYPE2_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE2;

SELECT COUNT(*) AS SCD_TYPE1_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE1;

SELECT
    COUNT(*) AS SCD_TYPE2_RECORD_COUNT,
    COUNT_IF(IS_CURRENT = TRUE) AS SCD_TYPE2_CURRENT_RECORD_COUNT,
    COUNT_IF(IS_CURRENT = FALSE) AS SCD_TYPE2_HISTORICAL_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE2;

SELECT
    CUSTOMER_ID,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_TYPE2
GROUP BY CUSTOMER_ID
HAVING COUNT_IF(IS_CURRENT = TRUE) <> 1;

SELECT
    CUSTOMER_ID,
    CUSTOMER_KEY,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE EFFECTIVE_DATE > EXPIRY_DATE;

SELECT
    CUSTOMER_ID,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = TRUE
  AND EXPIRY_DATE <> DATE '9999-12-31';

SELECT
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

SELECT
    'Old Value Preserved?' AS FEATURE,
    'No' AS TYPE_1,
    'Yes' AS TYPE_2

UNION ALL

SELECT
    'New Row Created?',
    'No',
    'Yes'

UNION ALL

SELECT
    'Historical Analysis?',
    'No',
    'Yes'

UNION ALL

SELECT
    'Effective Date',
    'No',
    'Yes'

UNION ALL

SELECT
    'Expiry Date',
    'No',
    'Yes'

UNION ALL

SELECT
    'IS_CURRENT',
    'No',
    'Yes'

UNION ALL

SELECT
    'Storage Required',
    'Lower',
    'Higher';

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE1
WHERE CUSTOMER_ID = 101;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;