USE WAREHOUSE PROJECT_11_WH;
USE DATABASE PROJECT_11_DB;
USE SCHEMA PROJECT_11_SCHEMA;

-----------FILE FORMAT CREATION
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE='CSV'
SKIP_HEADER=1;

------------------STAGE CREATION

CREATE OR REPLACE STAGE CUSTOMER_STAGE
FILE_FORMAT=CSV_FORMAT;

LIST @CUSTOMER_STAGE;

-----------------CREATE RAW TABLES
CREATE OR REPLACE TABLE RAW_CUSTOMERS_INITIAL
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    MEMBERSHIP VARCHAR,
    SEGMENT VARCHAR
);

CREATE OR REPLACE TABLE RAW_CUSTOMER_UPDATES
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    MEMBERSHIP VARCHAR,
    SEGMENT VARCHAR,
    EFFECTIVE_DATE DATE
);

-----------------------LOAD CSV FILES
COPY INTO RAW_CUSTOMERS_INITIAL
FROM @CUSTOMER_STAGE/customer_initial1.csv
FILE_FORMAT = CSV_FORMAT;

DESC TABLE RAW_CUSTOMER_UPDATES;

COPY INTO RAW_CUSTOMER_UPDATES
FROM @CUSTOMER_STAGE/customer_update1.csv
FILE_FORMAT = CSV_FORMAT;

---------------------CREATE THE HYBRID DIMENSION
CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    PREVIOUS_CITY VARCHAR,
    STATE VARCHAR,
    CURRENT_MEMBERSHIP VARCHAR,
    PREVIOUS_MEMBERSHIP VARCHAR,
    HISTORICAL_MEMBERSHIP VARCHAR,
    SEGMENT VARCHAR,
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    NULL AS PREVIOUS_CITY,
    STATE,
    MEMBERSHIP AS CURRENT_MEMBERSHIP,
    NULL AS PREVIOUS_MEMBERSHIP,
    MEMBERSHIP AS HISTORICAL_MEMBERSHIP,
    SEGMENT,
    '2026-01-01' AS EFFECTIVE_DATE,
    '9999-12-31' AS EXPIRY_DATE,
    TRUE AS IS_CURRENT
FROM RAW_CUSTOMERS_INITIAL;

-------------------------VALIDATING DATA

SELECT *
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID;

---------------CURRENT RECORD SNAPSHOT
CREATE OR REPLACE TEMP TABLE CUSTOMER_UPDATE_SNAPSHOT AS
SELECT
    D.CUSTOMER_ID,
    D.CUSTOMER_NAME,
    D.CITY AS OLD_CITY,
    D.STATE AS OLD_STATE,
    D.CURRENT_MEMBERSHIP AS OLD_MEMBERSHIP,
    D.SEGMENT AS OLD_SEGMENT,
    U.CITY AS NEW_CITY,
    U.STATE AS NEW_STATE,
    U.MEMBERSHIP AS NEW_MEMBERSHIP,
    U.SEGMENT AS NEW_SEGMENT,
    U.EFFECTIVE_DATE
FROM DIM_CUSTOMER_HYBRID D
JOIN RAW_CUSTOMER_UPDATES U
    ON D.CUSTOMER_ID = U.CUSTOMER_ID
WHERE D.IS_CURRENT = TRUE;

SELECT *
FROM CUSTOMER_UPDATE_SNAPSHOT
ORDER BY CUSTOMER_ID;

---------------------EXPIRE OLD RECORDS
UPDATE DIM_CUSTOMER_HYBRID D
SET
    EXPIRY_DATE = DATEADD(
        DAY,
        -1,
        S.EFFECTIVE_DATE
    ),
    IS_CURRENT = FALSE
FROM CUSTOMER_UPDATE_SNAPSHOT S
WHERE D.CUSTOMER_ID = S.CUSTOMER_ID
  AND D.IS_CURRENT = TRUE;

----------------VALIDATING EXPIRED RECORDS
SELECT
    CUSTOMER_ID,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = FALSE
ORDER BY CUSTOMER_ID;

---------------------------INSERT NEW ACTIVE RECORDS

INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,

    NEW_CITY AS CITY,

    CASE
        WHEN NEW_CITY <> OLD_CITY
        THEN OLD_CITY
        ELSE NULL
    END AS PREVIOUS_CITY,

    NEW_STATE AS STATE,

    NEW_MEMBERSHIP AS CURRENT_MEMBERSHIP,

    OLD_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,

    NEW_MEMBERSHIP AS HISTORICAL_MEMBERSHIP,

    NEW_SEGMENT AS SEGMENT,

    EFFECTIVE_DATE,

    '9999-12-31' AS EXPIRY_DATE,

    TRUE AS IS_CURRENT

FROM CUSTOMER_UPDATE_SNAPSHOT;

----------------------VALIDATING
SELECT *
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

-------------SYNCHRONISE GLOBAL CITY
UPDATE DIM_CUSTOMER_HYBRID D
SET
    CITY = S.NEW_CITY,
    PREVIOUS_CITY =
        CASE
            WHEN S.NEW_CITY <> S.OLD_CITY
            THEN S.OLD_CITY
            ELSE D.PREVIOUS_CITY
        END
FROM CUSTOMER_UPDATE_SNAPSHOT S
WHERE D.CUSTOMER_ID = S.CUSTOMER_ID;

--------------------SYNCHRONIZE STATE
UPDATE DIM_CUSTOMER_HYBRID D
SET
    STATE = S.NEW_STATE
FROM CUSTOMER_UPDATE_SNAPSHOT S
WHERE D.CUSTOMER_ID = S.CUSTOMER_ID;

-------------------SYNCHRONIZE CURRENT & PREVIOUS MEMBERSHIP
UPDATE DIM_CUSTOMER_HYBRID D
SET
    CURRENT_MEMBERSHIP = S.NEW_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP = S.OLD_MEMBERSHIP
FROM CUSTOMER_UPDATE_SNAPSHOT S
WHERE D.CUSTOMER_ID = S.CUSTOMER_ID;

--------------------FINAL VALIDATION
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

-----------------------------ACTIVE CUSTOMER REPORT
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

-----------------------------------What was Customer 101's historical membership, segment, and city on March 15, 2026?

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 101
  AND '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

------------------------FINAL METRIC VALIDATION
  SELECT
    COUNT(*) AS TOTAL_RECORD_COUNT,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_RECORD_COUNT,
    COUNT_IF(IS_CURRENT = FALSE) AS HISTORICAL_RECORD_COUNT
FROM DIM_CUSTOMER_HYBRID;