
CREATE OR REPLACE DATABASE RETAIL_SCHEMAS_DW;

USE DATABASE RETAIL_SCHEMAS_DW;

CREATE OR REPLACE SCHEMA SCHEMA_COMPARISON;

USE SCHEMA SCHEMA_COMPARISON;


CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;


CREATE OR REPLACE STAGE RETAIL_STAGE
FILE_FORMAT = CSV_FORMAT;


LIST @RETAIL_STAGE;


CREATE OR REPLACE TABLE STG_REGIONS_AND_STORES (
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION_NAME VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);


CREATE OR REPLACE TABLE STG_PRODUCT_HIERARCHY (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_NAME VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);


CREATE OR REPLACE TABLE STG_CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50)
);


CREATE OR REPLACE TABLE STG_SALES_TRANSACTIONS (
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID NUMBER,
    STORE_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2)
);


COPY INTO STG_REGIONS_AND_STORES
FROM @RETAIL_STAGE/regions_and_stores.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO STG_PRODUCT_HIERARCHY
FROM @RETAIL_STAGE/product_hierarchy.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO STG_CUSTOMERS
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO STG_SALES_TRANSACTIONS
FROM @RETAIL_STAGE/sales_transactions.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';


CREATE OR REPLACE TABLE STAR_DIM_STORE (
    STORE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION_NAME VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);


CREATE OR REPLACE TABLE STAR_DIM_PRODUCT (
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_NAME VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);


INSERT INTO STAR_DIM_STORE (
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_NAME,
    REGIONAL_MANAGER
)
SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_NAME,
    REGIONAL_MANAGER
FROM STG_REGIONS_AND_STORES;


INSERT INTO STAR_DIM_PRODUCT (
    PRODUCT_ID,
    PRODUCT_NAME,
    SUBCATEGORY_NAME,
    CATEGORY_NAME,
    UNIT_PRICE
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    SUBCATEGORY_NAME,
    CATEGORY_NAME,
    UNIT_PRICE
FROM STG_PRODUCT_HIERARCHY;


CREATE OR REPLACE TABLE STAR_FACT_SALES (
    SALES_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID NUMBER,
    STORE_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2),
    FOREIGN KEY (STORE_KEY) REFERENCES STAR_DIM_STORE(STORE_KEY),
    FOREIGN KEY (PRODUCT_KEY) REFERENCES STAR_DIM_PRODUCT(PRODUCT_KEY)
);


INSERT INTO STAR_FACT_SALES (
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_ID,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    s.TRANSACTION_ID,
    s.TRANSACTION_DATE,
    s.CUSTOMER_ID,
    ds.STORE_KEY,
    dp.PRODUCT_KEY,
    s.QUANTITY,
    s.QUANTITY * s.UNIT_PRICE
FROM STG_SALES_TRANSACTIONS s
JOIN STAR_DIM_STORE ds
    ON s.STORE_ID = ds.STORE_ID
JOIN STAR_DIM_PRODUCT dp
    ON s.PRODUCT_ID = dp.PRODUCT_ID;


CREATE OR REPLACE TABLE SNOW_DIM_REGION (
    REGION_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    REGION_NAME VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);


CREATE OR REPLACE TABLE SNOW_DIM_STORE (
    STORE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION_KEY NUMBER,
    FOREIGN KEY (REGION_KEY) REFERENCES SNOW_DIM_REGION(REGION_KEY)
);


CREATE OR REPLACE TABLE SNOW_DIM_CATEGORY (
    CATEGORY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50)
);


CREATE OR REPLACE TABLE SNOW_DIM_SUBCATEGORY (
    SUBCATEGORY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_KEY NUMBER,
    FOREIGN KEY (CATEGORY_KEY) REFERENCES SNOW_DIM_CATEGORY(CATEGORY_KEY)
);


CREATE OR REPLACE TABLE SNOW_DIM_PRODUCT (
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    UNIT_PRICE NUMBER(10,2),
    SUBCATEGORY_KEY NUMBER,
    FOREIGN KEY (SUBCATEGORY_KEY) REFERENCES SNOW_DIM_SUBCATEGORY(SUBCATEGORY_KEY)
);


INSERT INTO SNOW_DIM_REGION (
    REGION_NAME,
    REGIONAL_MANAGER
)
SELECT DISTINCT
    REGION_NAME,
    REGIONAL_MANAGER
FROM STG_REGIONS_AND_STORES;


INSERT INTO SNOW_DIM_STORE (
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_KEY
)
SELECT
    s.STORE_ID,
    s.STORE_NAME,
    s.CITY,
    s.STATE,
    r.REGION_KEY
FROM STG_REGIONS_AND_STORES s
JOIN SNOW_DIM_REGION r
    ON TRIM(LOWER(s.REGION_NAME)) = TRIM(LOWER(r.REGION_NAME))
   AND TRIM(LOWER(s.REGIONAL_MANAGER)) = TRIM(LOWER(r.REGIONAL_MANAGER));


INSERT INTO SNOW_DIM_CATEGORY (
    CATEGORY_NAME
)
SELECT DISTINCT
    CATEGORY_NAME
FROM STG_PRODUCT_HIERARCHY;


INSERT INTO SNOW_DIM_SUBCATEGORY (
    SUBCATEGORY_NAME,
    CATEGORY_KEY
)
SELECT DISTINCT
    p.SUBCATEGORY_NAME,
    c.CATEGORY_KEY
FROM STG_PRODUCT_HIERARCHY p
JOIN SNOW_DIM_CATEGORY c
    ON TRIM(LOWER(p.CATEGORY_NAME)) = TRIM(LOWER(c.CATEGORY_NAME));


INSERT INTO SNOW_DIM_PRODUCT (
    PRODUCT_ID,
    PRODUCT_NAME,
    UNIT_PRICE,
    SUBCATEGORY_KEY
)
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.UNIT_PRICE,
    sc.SUBCATEGORY_KEY
FROM STG_PRODUCT_HIERARCHY p
JOIN SNOW_DIM_SUBCATEGORY sc
    ON TRIM(LOWER(p.SUBCATEGORY_NAME)) = TRIM(LOWER(sc.SUBCATEGORY_NAME));


CREATE OR REPLACE TABLE SNOW_FACT_SALES (
    SALES_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID NUMBER,
    STORE_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2),
    FOREIGN KEY (STORE_KEY) REFERENCES SNOW_DIM_STORE(STORE_KEY),
    FOREIGN KEY (PRODUCT_KEY) REFERENCES SNOW_DIM_PRODUCT(PRODUCT_KEY)
);


INSERT INTO SNOW_FACT_SALES (
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_ID,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    s.TRANSACTION_ID,
    s.TRANSACTION_DATE,
    s.CUSTOMER_ID,
    ds.STORE_KEY,
    dp.PRODUCT_KEY,
    s.QUANTITY,
    s.QUANTITY * s.UNIT_PRICE
FROM STG_SALES_TRANSACTIONS s
JOIN SNOW_DIM_STORE ds
    ON s.STORE_ID = ds.STORE_ID
JOIN SNOW_DIM_PRODUCT dp
    ON s.PRODUCT_ID = dp.PRODUCT_ID;


SELECT
    ds.REGION_NAME,
    dp.CATEGORY_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM STAR_FACT_SALES f
JOIN STAR_DIM_STORE ds
    ON f.STORE_KEY = ds.STORE_KEY
JOIN STAR_DIM_PRODUCT dp
    ON f.PRODUCT_KEY = dp.PRODUCT_KEY
GROUP BY
    ds.REGION_NAME,
    dp.CATEGORY_NAME
ORDER BY
    ds.REGION_NAME,
    dp.CATEGORY_NAME;


SELECT
    r.REGION_NAME,
    c.CATEGORY_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SNOW_FACT_SALES f
JOIN SNOW_DIM_STORE s
    ON f.STORE_KEY = s.STORE_KEY
JOIN SNOW_DIM_REGION r
    ON s.REGION_KEY = r.REGION_KEY
JOIN SNOW_DIM_PRODUCT p
    ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN SNOW_DIM_SUBCATEGORY sc
    ON p.SUBCATEGORY_KEY = sc.SUBCATEGORY_KEY
JOIN SNOW_DIM_CATEGORY c
    ON sc.CATEGORY_KEY = c.CATEGORY_KEY
GROUP BY
    r.REGION_NAME,
    c.CATEGORY_NAME
ORDER BY
    r.REGION_NAME,
    c.CATEGORY_NAME;


SELECT
    'Star Schema' AS SCHEMA_TYPE,
    'STAR_DIM_STORE' AS TABLE_NAME,
    COUNT(*) AS RECORD_COUNT
FROM STAR_DIM_STORE

UNION ALL

SELECT
    'Star Schema',
    'STAR_DIM_PRODUCT',
    COUNT(*)
FROM STAR_DIM_PRODUCT

UNION ALL

SELECT
    'Star Schema',
    'STAR_FACT_SALES',
    COUNT(*)
FROM STAR_FACT_SALES

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_REGION',
    COUNT(*)
FROM SNOW_DIM_REGION

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_STORE',
    COUNT(*)
FROM SNOW_DIM_STORE

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_CATEGORY',
    COUNT(*)
FROM SNOW_DIM_CATEGORY

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_SUBCATEGORY',
    COUNT(*)
FROM SNOW_DIM_SUBCATEGORY

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_PRODUCT',
    COUNT(*)
FROM SNOW_DIM_PRODUCT

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_FACT_SALES',
    COUNT(*)
FROM SNOW_FACT_SALES;


SELECT
    'Dimension Normalization Level' AS METRIC_FEATURE,
    'Denormalized (Flat)' AS STAR_SCHEMA,
    'Normalized (Hierarchical)' AS SNOWFLAKE_SCHEMA

UNION ALL

SELECT
    'Total Dimension Tables',
    '2 Tables',
    '5 Tables'

UNION ALL

SELECT
    'Joins for Category Revenue',
    '2 Joins (Fact + 2 Dims)',
    '5 Joins (Fact + 5 Tables)'

UNION ALL

SELECT
    'Data Redundancy',
    'Higher (Repeated text)',
    'Lower (Normalized IDs)'

UNION ALL

SELECT
    'Query Simplicity',
    'High (Simple GROUP BY)',
    'Lower (Requires nested FKs)';


SELECT
    ds.REGIONAL_MANAGER,
    SUM(f.QUANTITY) AS TOTAL_ITEMS_SOLD,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_SALES_AMOUNT
FROM STAR_FACT_SALES f
JOIN STAR_DIM_STORE ds
    ON f.STORE_KEY = ds.STORE_KEY
GROUP BY
    ds.REGIONAL_MANAGER
ORDER BY
    ds.REGIONAL_MANAGER;


SELECT
    'STAR_SCHEMA' AS SCHEMA_TYPE,
    'STAR_DIM_STORE' AS TABLE_NAME,
    COUNT(*) AS RECORD_COUNT
FROM STAR_DIM_STORE

UNION ALL

SELECT
    'STAR_SCHEMA',
    'STAR_DIM_PRODUCT',
    COUNT(*)
FROM STAR_DIM_PRODUCT

UNION ALL

SELECT
    'STAR_SCHEMA',
    'STAR_FACT_SALES',
    COUNT(*)
FROM STAR_FACT_SALES

UNION ALL

SELECT
    'SNOWFLAKE_SCHEMA',
    'SNOW_DIM_REGION',
    COUNT(*)
FROM SNOW_DIM_REGION

UNION ALL

SELECT
    'SNOWFLAKE_SCHEMA',
    'SNOW_DIM_STORE',
    COUNT(*)
FROM SNOW_DIM_STORE

UNION ALL

SELECT
    'SNOWFLAKE_SCHEMA',
    'SNOW_DIM_CATEGORY',
    COUNT(*)
FROM SNOW_DIM_CATEGORY

UNION ALL

SELECT
    'SNOWFLAKE_SCHEMA',
    'SNOW_DIM_SUBCATEGORY',
    COUNT(*)
FROM SNOW_DIM_SUBCATEGORY

UNION ALL

SELECT
    'SNOWFLAKE_SCHEMA',
    'SNOW_DIM_PRODUCT',
    COUNT(*)
FROM SNOW_DIM_PRODUCT

UNION ALL

SELECT
    'SNOWFLAKE_SCHEMA',
    'SNOW_FACT_SALES',
    COUNT(*)
FROM SNOW_FACT_SALES;

