CREATE OR REPLACE WAREHOUSE SNOW_WH
WAREHOUSE_SIZE = 'X-SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE SNOW_WH;

CREATE OR REPLACE DATABASE CUSTOMER_HISTORY_DW;

USE DATABASE CUSTOMER_HISTORY_DW;

CREATE OR REPLACE SCHEMA CUSTOMER_SCHEMA;

USE SCHEMA CUSTOMER_SCHEMA;


CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE CUSTOMER_STAGE
FILE_FORMAT = CUSTOMER_CSV_FORMAT;

LIST @CUSTOMER_STAGE;

CREATE OR REPLACE TABLE STG_CUSTOMERS_INITIAL (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);


/* =====================================================================
   TASK 5: CREATE STAGING TABLE FOR CUSTOMER UPDATES
   ===================================================================== */

CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);


/* =====================================================================
   TASK 6: CREATE DIM_CUSTOMER

   CUSTOMER_KEY = SURROGATE KEY
   CUSTOMER_ID  = BUSINESS / NATURAL KEY

   At this stage we intentionally maintain only ONE record per customer.
   This is the current design that causes historical data loss.
   ===================================================================== */

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);


/* =====================================================================
   TASK 7: LOAD INITIAL CUSTOMER DATA

   Upload customers_initial.csv into @CUSTOMER_STAGE before running
   the COPY command below.
   ===================================================================== */

COPY INTO STG_CUSTOMERS_INITIAL
FROM @CUSTOMER_STAGE/customers_initial.csv
FILE_FORMAT = CUSTOMER_CSV_FORMAT;


/* =====================================================================
   TASK 8: VALIDATE INITIAL STAGING DATA
   ===================================================================== */

SELECT
    COUNT(*) AS INITIAL_CUSTOMER_COUNT
FROM STG_CUSTOMERS_INITIAL;


INSERT INTO DIM_CUSTOMER (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM STG_CUSTOMERS_INITIAL;

SELECT
    COUNT(*) AS TOTAL_CUSTOMERS
FROM DIM_CUSTOMER;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

COPY INTO CUSTOMER_UPDATES
FROM @CUSTOMER_STAGE/customer_updates.csv
FILE_FORMAT = CUSTOMER_CSV_FORMAT;

SELECT
    COUNT(*) AS UPDATE_RECORDS_RECEIVED
FROM CUSTOMER_UPDATES;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID;

SELECT
    C.CUSTOMER_ID,

    C.CITY AS OLD_CITY,
    U.CITY AS NEW_CITY,

    C.STATE AS OLD_STATE,
    U.STATE AS NEW_STATE,

    C.MEMBERSHIP AS OLD_MEMBERSHIP,
    U.MEMBERSHIP AS NEW_MEMBERSHIP,

    C.SEGMENT AS OLD_SEGMENT,
    U.SEGMENT AS NEW_SEGMENT

FROM DIM_CUSTOMER C

JOIN CUSTOMER_UPDATES U
    ON C.CUSTOMER_ID = U.CUSTOMER_ID

WHERE
       NVL(C.CITY, '') <> NVL(U.CITY, '')
    OR NVL(C.STATE, '') <> NVL(U.STATE, '')
    OR NVL(C.MEMBERSHIP, '') <> NVL(U.MEMBERSHIP, '')
    OR NVL(C.SEGMENT, '') <> NVL(U.SEGMENT, '')

ORDER BY C.CUSTOMER_ID;

SELECT
    C.CUSTOMER_ID,
    'CITY' AS ATTRIBUTE,
    C.CITY AS OLD_VALUE,
    U.CITY AS NEW_VALUE
FROM DIM_CUSTOMER C
JOIN CUSTOMER_UPDATES U
    ON C.CUSTOMER_ID = U.CUSTOMER_ID
WHERE NVL(C.CITY, '') <> NVL(U.CITY, '')

UNION ALL

SELECT
    C.CUSTOMER_ID,
    'STATE' AS ATTRIBUTE,
    C.STATE AS OLD_VALUE,
    U.STATE AS NEW_VALUE
FROM DIM_CUSTOMER C
JOIN CUSTOMER_UPDATES U
    ON C.CUSTOMER_ID = U.CUSTOMER_ID
WHERE NVL(C.STATE, '') <> NVL(U.STATE, '')

UNION ALL

SELECT
    C.CUSTOMER_ID,
    'MEMBERSHIP' AS ATTRIBUTE,
    C.MEMBERSHIP AS OLD_VALUE,
    U.MEMBERSHIP AS NEW_VALUE
FROM DIM_CUSTOMER C
JOIN CUSTOMER_UPDATES U
    ON C.CUSTOMER_ID = U.CUSTOMER_ID
WHERE NVL(C.MEMBERSHIP, '') <> NVL(U.MEMBERSHIP, '')

UNION ALL

SELECT
    C.CUSTOMER_ID,
    'SEGMENT' AS ATTRIBUTE,
    C.SEGMENT AS OLD_VALUE,
    U.SEGMENT AS NEW_VALUE
FROM DIM_CUSTOMER C
JOIN CUSTOMER_UPDATES U
    ON C.CUSTOMER_ID = U.CUSTOMER_ID
WHERE NVL(C.SEGMENT, '') <> NVL(U.SEGMENT, '')

ORDER BY CUSTOMER_ID, ATTRIBUTE;

UPDATE DIM_CUSTOMER C

SET
    CUSTOMER_NAME = U.CUSTOMER_NAME,
    CITY = U.CITY,
    STATE = U.STATE,
    MEMBERSHIP = U.MEMBERSHIP,
    SEGMENT = U.SEGMENT

FROM CUSTOMER_UPDATES U

WHERE C.CUSTOMER_ID = U.CUSTOMER_ID;


/* =====================================================================
   TASK 18: DISPLAY UPDATED DIMENSION
   ===================================================================== */

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101;

SELECT *
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101
  AND CITY = 'Hyderabad'
  AND STATE = 'Telangana'
  AND MEMBERSHIP = 'Silver';

UPDATE DIM_CUSTOMER C

SET
    CUSTOMER_NAME = U.CUSTOMER_NAME,
    CITY = U.CITY,
    STATE = U.STATE,
    MEMBERSHIP = U.MEMBERSHIP,
    SEGMENT = U.SEGMENT

FROM CUSTOMER_UPDATES U

WHERE C.CUSTOMER_ID = U.CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101;


SELECT *
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101
  AND CITY = 'Hyderabad'
  AND STATE = 'Telangana'
  AND MEMBERSHIP = 'Silver';

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID IN (101, 103, 104)
ORDER BY CUSTOMER_ID;


SELECT
    COUNT(*) AS TOTAL_CUSTOMERS,
    COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM DIM_CUSTOMER;

SELECT
    CUSTOMER_ID,
    COUNT(*) AS RECORD_COUNT
FROM DIM_CUSTOMER
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;


DESC TABLE DIM_CUSTOMER;

SHOW TABLES;