USE WAREHOUSE PROJECT_12_WH;
USE DATABASE PROJECT_12_RETAIL_DB;
USE SCHEMA SALES_ANALYTICS_12;
-------------FILE FORMAT CREATION
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE='CSV'
SKIP_HEADER=1;

------------STAGE CREATION
CREATE OR REPLACE STAGE RETAIL_STAGE
FILE_FORMAT=CSV_FORMAT;


----------------CREATING RAW TABLES

CREATE OR REPLACE TABLE RAW_STORES
(
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    STORE_MANAGER VARCHAR(100)
);

COPY INTO RAW_STORES
FROM @RETAIL_STAGE/stores.csv
FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE TABLE RAW_PRODUCTS
(
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);

COPY INTO RAW_PRODUCTS
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE TABLE RAW_CUSTOMERS_INITIAL
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);

COPY INTO RAW_CUSTOMERS_INITIAL
FROM @RETAIL_STAGE/customer_initial.csv
FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE TABLE RAW_CUSTOMER_UPDATES
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);

COPY INTO RAW_CUSTOMER_UPDATES
FROM @RETAIL_STAGE/customer_update.csv
FILE_FORMAT =  CSV_FORMAT;


--------------------- CREATING STORE DINMENSION

CREATE OR REPLACE TABLE DIM_STORE
(
    STORE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    STORE_MANAGER VARCHAR(100)
);

---------------------CREATING PRODUCT DIMENSION
CREATE OR REPLACE TABLE DIM_PRODUCT
(
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);

-------------------CREATING HYBRID CUSTOMER DIMENSION

CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    PREVIOUS_CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

---------------------POPULATING DIMENSION TABLES
INSERT INTO DIM_STORE
(
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
)
SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
FROM RAW_STORES;

SELECT * FROM DIM_STORE;

--------------------------POPULATING DIM_PRODUCT TABLE
INSERT INTO DIM_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
FROM RAW_PRODUCTS;

SELECT * FROM DIM_PRODUCT;

-------------------POPULATING HYBRID CUSTOMER
INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    NULL AS PREVIOUS_CITY,
    STATE,
    MEMBERSHIP AS CURRENT_MEMBERSHIP,
    NULL AS PREVIOUS_MEMBERSHIP,
    MEMBERSHIP AS HISTORICAL_MEMBERSHIP,
    SEGMENT,
    '2026-01-01' AS EFFECTIVE_DATE,
    '9999-12-31' AS EXPIRY_DATE,
    TRUE AS IS_CURRENT
FROM RAW_CUSTOMERS_INITIAL;

SELECT *
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID;

---------------------------FACT TABLE FACT_SALES CREATION
CREATE OR REPLACE TABLE FACT_SALES
(
    SALES_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_KEY NUMBER,
    STORE_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    TOTAL_AMOUNT NUMBER(12,2),

    FOREIGN KEY (CUSTOMER_KEY)
        REFERENCES DIM_CUSTOMER_HYBRID(CUSTOMER_KEY),

    FOREIGN KEY (STORE_KEY)
        REFERENCES DIM_STORE(STORE_KEY),

    FOREIGN KEY (PRODUCT_KEY)
        REFERENCES DIM_PRODUCT(PRODUCT_KEY)
);

-----------------INSERTING Q1 SALES
INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-1001',
    '2026-02-15',
    C.CUSTOMER_KEY,
    S.STORE_KEY,
    P.PRODUCT_KEY,
    1,
    P.UNIT_PRICE,
    1 * P.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID C
JOIN DIM_STORE S
    ON S.STORE_ID = 201
JOIN DIM_PRODUCT P
    ON P.PRODUCT_ID = 501
WHERE C.CUSTOMER_ID = 101
  AND C.IS_CURRENT = TRUE;

------------INSERTING TXN-1002
INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-1002',
    '2026-03-10',
    C.CUSTOMER_KEY,
    S.STORE_KEY,
    P.PRODUCT_KEY,
    2,
    P.UNIT_PRICE,
    2 * P.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID C
JOIN DIM_STORE S
    ON S.STORE_ID = 203
JOIN DIM_PRODUCT P
    ON P.PRODUCT_ID = 502
WHERE C.CUSTOMER_ID = 103
  AND C.IS_CURRENT = TRUE;

----------STORE MANAGER SCD TYPE 1
UPDATE DIM_STORE
SET STORE_MANAGER = 'Suresh Menon'
WHERE STORE_ID = 201;

SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
FROM DIM_STORE
WHERE STORE_ID = 201;

----------------Execute Multi-Attribute Customer Updates

-- 1.eXPIRING OLD RECORD
UPDATE DIM_CUSTOMER_HYBRID C
SET
    EXPIRY_DATE = DATEADD(DAY, -1, U.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM RAW_CUSTOMER_UPDATES U
WHERE C.CUSTOMER_ID = U.CUSTOMER_ID
  AND C.IS_CURRENT = TRUE;

-- 2.iNSERTING NEW RECORDS
INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    U.CUSTOMER_ID,
    U.CUSTOMER_NAME,
    U.CITY,
    OLD.CITY AS PREVIOUS_CITY,
    U.STATE,
    U.MEMBERSHIP AS CURRENT_MEMBERSHIP,
    OLD.CURRENT_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,
    U.MEMBERSHIP AS HISTORICAL_MEMBERSHIP,
    U.SEGMENT,
    U.EFFECTIVE_DATE,
    '9999-12-31' AS EXPIRY_DATE,
    TRUE AS IS_CURRENT
FROM RAW_CUSTOMER_UPDATES U
JOIN DIM_CUSTOMER_HYBRID OLD
    ON U.CUSTOMER_ID = OLD.CUSTOMER_ID
WHERE OLD.EXPIRY_DATE =
      DATEADD(DAY, -1, U.EFFECTIVE_DATE);

-- 3.VALIDATING
SELECT
    CUSTOMER_ID,
    CUSTOMER_KEY,
    CITY,
    PREVIOUS_CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

-- 4. SYNCHRONIZE CURRENT ATTRIBUTES

UPDATE DIM_CUSTOMER_HYBRID C
SET
    CITY = U.CITY,
    STATE = U.STATE,
    CURRENT_MEMBERSHIP = U.MEMBERSHIP,
    PREVIOUS_MEMBERSHIP = I.MEMBERSHIP,
    PREVIOUS_CITY =
        CASE
            WHEN I.CITY <> U.CITY
            THEN I.CITY
            ELSE NULL
        END
FROM RAW_CUSTOMERS_INITIAL I
JOIN RAW_CUSTOMER_UPDATES U
    ON I.CUSTOMER_ID = U.CUSTOMER_ID
WHERE C.CUSTOMER_ID = I.CUSTOMER_ID;

------------------- INSERT TXN-2001
INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-2001',
    '2026-04-15',
    C.CUSTOMER_KEY,
    S.STORE_KEY,
    P.PRODUCT_KEY,
    1,
    P.UNIT_PRICE,
    1 * P.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID C
JOIN DIM_STORE S
    ON S.STORE_ID = 201
JOIN DIM_PRODUCT P
    ON P.PRODUCT_ID = 503
WHERE C.CUSTOMER_ID = 101
  AND C.IS_CURRENT = TRUE;

----------------------CHECK CUSTOMER HISTORY
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY
    CUSTOMER_ID,
    EFFECTIVE_DATE;

-- Point-in-Time Point-of-Sale Analytics

SELECT
    F.TRANSACTION_ID,
    F.TRANSACTION_DATE,
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY AS CURRENT_CITY,
    C.HISTORICAL_MEMBERSHIP AS MEMBERSHIP_AT_PURCHASE,
    C.SEGMENT AS SEGMENT_AT_PURCHASE,
    S.STORE_NAME,
    P.PRODUCT_NAME,
    F.TOTAL_AMOUNT
FROM FACT_SALES F
JOIN DIM_CUSTOMER_HYBRID C
    ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
JOIN DIM_STORE S
    ON F.STORE_KEY = S.STORE_KEY
JOIN DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY
WHERE C.CUSTOMER_ID = 101
ORDER BY F.TRANSACTION_DATE;

-- WAREHOUSE RECORD COUNT & DATA AUDIT

SELECT
    'STORE DIMENSION RECORDS' AS METRIC,
    COUNT(*) AS VALUE
FROM DIM_STORE

UNION ALL

SELECT
    'PRODUCT DIMENSION RECORDS',
    COUNT(*)
FROM DIM_PRODUCT

UNION ALL

SELECT
    'TOTAL CUSTOMER DIMENSION RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID

UNION ALL

SELECT
    'CURRENT CUSTOMER RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE

UNION ALL

SELECT
    'HISTORICAL CUSTOMER RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = FALSE

UNION ALL

SELECT
    'FACT SALES TRANSACTIONS',
    COUNT(*)
FROM FACT_SALES;
